Add Missing Icons
fyne-io/fyne pull request #1586
Opened 2020-11-20 00:49 UTC by AlbinoGeek

## Description:
Added some useful icons that were missing from the existing groups:
- Check Box Indeterminate
- Document Rename
- Media Stop
- Upload

And one new ungrouped icon:
- Refresh

### Checklist:

- [X] Lint and formatter run with no errors.
- [X] Tests all pass.

2020-11-20 01:56 UTC, AlbinoGeek commented
Ahh, I missed where they were referenced as public functions -- fixing that next.

2020-11-20 01:59 UTC, stuartmscott reviewed
Thanks for taking the time to make this contribution @AlbinoGeek

The `media-stop` and `upload` icons make perfect sense and I would happily approve their addition to this project.

I have seen the `check-box-indeterminate` icon used in the MD spec for checkboxes with a parent-child relationship, however this is not something Fyne checkboxes support at this time. Therefore I'd be tempted to hold off on adding this icon until that support is added, unless there is another compelling reason to add it now.

I do not think the new `document-rename` icon and the existing `document-create` icon go together well.

I'm not sure how the new `refresh` icon differs from the existing `view-refresh` icon.

2020-11-20 01:59 UTC, stuartmscott commented on theme/gen.go
> +	bundleIcon("refresh", f)
Is this different from view-refresh?

2020-11-20 09:44 UTC, andydotxyz commented
I agree with @stuartmscott comments, thanks.
Also could you add the icons to the "Theme Icons" section of `cmd/fyne_demo` please?

2020-11-20 13:00 UTC, AlbinoGeek commented on theme/gen.go
> +	bundleIcon("refresh", f)
Correct -- sorry about that.

2020-11-20 13:03 UTC, AlbinoGeek commented
The issue I ran into is that `file-` in fyne currently references `content type metadata` and not... literal file operations, which has been a little confusing when it comes to selecting matching icons from Material Design.

There were a lot of icons I really wanted but simply could not suggest adding because they were only available in outline format, such as `cloud_folder_upload` -- this was one of those issues, where I don't think we have any semantic representation of a `rename` operation at the moment, but could not find a matching icon.

`drive-file-rename-outline` being the only other semantic rename I could find, but it was also a non-matching icon.

Perhaps that should wait until the move to outline icons then.

---

Good points on `check-box-indeterminate`, as this is not a feature currently implemented in fyne. The other use-case to markdown specification is `CheckGroup` logic, in the sense that you have a UI containing multiple check-boxes, and a header which has a matching check box which implements "Select/Deselect All" logic -- which would then have the indeterminate state if "some but not all" items were selected.

---

Fixing that all now.

2020-11-20 14:08 UTC, stuartmscott submitted a review, later dismissed
Great work @AlbinoGeek, thanks for you contribution!

Its worth noting that if you have a need for an icon which doesn't make sense to bundle in the Fyne toolkit, you can bundle it into you app's code base instead

2020-11-20 20:41 UTC, andydotxyz commented
I think there is a copy/paste bug:

![Screenshot 2020-11-20 at 20 40 34](https://user-images.githubusercontent.com/294436/99847892-b18be900-2b70-11eb-9a4a-ea17b7bde551.png)

2020-11-20 20:41 UTC, andydotxyz requested changes

2020-11-20 20:41 UTC, andydotxyz commented on cmd/fyne_demo/tutorials/icons.go
> +	{"MediaStop", theme.MediaPlayIcon()},
Wrong icon

2020-11-20 23:20 UTC, AlbinoGeek commented on cmd/fyne_demo/tutorials/icons.go
> +	{"MediaStop", theme.MediaPlayIcon()},
Good catch! Bad copy/paste for sure.

2020-11-20 23:52 UTC, AlbinoGeek commented
* rebased onto `develop` after `release/v1.4.x` merge

2020-11-21 10:39 UTC, Jacalz approved these changes

2020-11-21 12:17 UTC, AlbinoGeek commented
Is there still a requested change? I can't see it.

2020-11-21 13:13 UTC, andydotxyz approved these changes

2020-11-21 13:55 UTC, merged

2020-11-25 10:46 UTC, andydotxyz commented
For the indeterminate checkbox there will be an example in the upcoming Fyne book :)