Expose MiddleMouseButton on desktop
fyne-io/fyne pull request #1619
Opened 2020-11-29 09:53 UTC by MagicalTux

making it the third option so RightMouseButton stays the same, also use glfw values for left/right instead of Button1 and Button2

### Description:
This adds MiddleMouseButton, and changes `glfw.MouseButton1` and 2 to `glfw.MouseButtonLeft` and `glfw.MouseButtonRight` which are easier to read.

No matching issue, but the middle mouse button was commented with TODO.

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [x] Tests all pass.

2020-11-29 10:09 UTC, andydotxyz requested changes
Nice addition, just missing the flag for new API

2020-11-29 10:09 UTC, andydotxyz commented on driver/desktop/mouse.go
> +	MiddleMouseButton
Please add Since: 2.0.0

2020-11-29 14:42 UTC, toaster requested changes
While “left” and “right” are easier to read than “1” and “2”, the name is misleading because for left-handed people it’s the other way around.
Maybe “first”, “second” and “third” is a better choice?
Also, what if we want to support additional mouse buttons? My MX Anywhere has two additional buttons (if I don’t count left/right of the scroll wheel).

2020-11-29 16:26 UTC, AlbinoGeek commented
I have a Flight stick with 38 buttons that Linux detects as a mouse ❌

2020-11-29 22:11 UTC, andydotxyz commented
>  for left-handed people it’s the other way around

This is a good point. GLFW just hard-codes Left to 1

2020-11-29 22:12 UTC, andydotxyz commented on driver/desktop/mouse.go
> +	MiddleMouseButton
Sorry I should have been more specific.
Like the Deprecated: lines specified by Go, this needs to be on a newline

2020-11-29 22:14 UTC, andydotxyz commented
Apologies I did not flag this first time @MagicalTux but a small test would be good - even just to check the convert function

2020-11-30 07:03 UTC, toaster commented
> > for left-handed people it’s the other way around
> 
> This is a good point. GLFW just hard-codes Left to 1

They probably did so because of @AlbinoGeek 's 38 button mouse and the OS changing the meaning all the time ;).

2020-12-02 15:14 UTC, andydotxyz commented
@stuartmscott pointed out that "MouseButtonPrimary" would be in-keeping with our naming elsewhere, but this PR is not setting up our API for left/right etc, but making use of the GLFW terms, so I don't think it's problematic to leave it as is (1, 2 etc) and review left vs right in a future PR that considers how we better support left handed mice.

2020-12-03 06:53 UTC, toaster commented
> @stuartmscott pointed out that "MouseButtonPrimary" would be in-keeping with our naming […].

I thought about this, too, but gave up when I didn’t know the word for the third button let alone the other 35 buttons of @MagicalTux mouse.

2020-12-03 06:54 UTC, toaster approved these changes

2020-12-03 15:13 UTC, stuartmscott commented
> I thought about this, too, but gave up when I didn’t know the word for the third button let alone the other 35 buttons of @MagicalTux mouse.

Seems an outlier, most mice have fewer than 10 buttons, and this PR is not trying to support that many buttons anyway. I'd say it will suffice to just add 3; `primary, secondary, tertiary` corresponding to `left, right, middle` for a right-handed user.

Longer term we could use names for the first 10;
`primary, secondary, tertiary, quaternary, quinary, senary, septenary, octonary, nonary denary`
and then introduce another type `MouseButtonExtended` that can hold any larger button ID.

2020-12-04 15:00 UTC, andydotxyz commented
Not sure that it makese sense naming the buttons > 3... Primary is a clear function, secondary another and in some products there is a tertiary button. But beyond that it really is button mappings to a number.

2020-12-04 15:27 UTC, andydotxyz approved these changes

2020-12-04 15:28 UTC, merged