RFC: container.New() and container.NewWithoutLayout()
fyne-io/fyne pull request #1637
Opened 2020-12-08 17:52 UTC by Jacalz

### Description:

This is a proposal about adding `container.New()` and `container.NewWithoutLayout()` to the container package, like discussed.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style.
- [x] Any breaking changes have a deprecation path or have been discussed.

2020-12-08 18:42 UTC, andydotxyz commented
Thanks for this, seems like a good idea.
However I'm having second thoughts about the `NewWithoutLayout` naming - without the `NewWithLayout` alongside it doesn't seem quite as logical - could a shorter version be found?

2020-12-08 18:49 UTC, stuartmscott commented
I thought the same, perhaps `New` and `NewWithLayout` would be better, though it implies the default is to use a container without a layout :/

2020-12-08 18:53 UTC, andydotxyz commented
Nah, the default certainly needs to be with-layout.
I guess `NewManual` or something like that would fit the naming in this package?

2020-12-08 19:16 UTC, stuartmscott commented
Maybe we're conflating two separate things. I agree container with layout should be the default. Do we need to support container without a layout, what are the use cases?

2020-12-08 22:29 UTC, andydotxyz commented
Yes we need to support a container without layout. It's called "Manual layout" and is a way for people to position items in a container individually - whereas a layout would work on the anonymous slice of elements.

2020-12-08 22:39 UTC, stuartmscott commented
How is that different from `fyne.NewContainerWithLayout(MyCustomLayout(), items...)`?

2020-12-09 09:17 UTC, andydotxyz commented
> How is that different from `fyne.NewContainerWithLayout(MyCustomLayout(), items...)`?

Well, like I thought I said - manual layout operates on individual named elements, a layout operates on an anonymous slice of elements.

Maybe think of `WithoutLayout` like the Swing `nil` layout? It's a useful way to control small areas or drawing elements.

2020-12-09 10:27 UTC, Jacalz commented
I think that I would prefer going with `.New()` and `.NewManual()`. It is the best names we have, in my opinion at least.

2020-12-09 11:19 UTC, andydotxyz commented
> I think that I would prefer going with `.New()` and `.NewManual()`

I think that's pretty clear and concise, happy to go with that.

2020-12-09 16:31 UTC, stuartmscott commented
What value does it provide other than being a struct containing a slice of fyne.CanvasObject?

2020-12-09 16:40 UTC, andydotxyz commented
No other value that I can think of. The `fyne.Container` exists to include multiple elements where otherwise only one would be possible.
Usually this contains a layout to help arrange these, but it is not required.

2020-12-09 16:48 UTC, Jacalz commented
Updated this PR with new naming.

2020-12-09 17:06 UTC, stuartmscott requested changes
I disagree with the 'manual' naming. Manual implies the alternative is Automatic, and as all of this is code nothing happens manually ie there is no human work to lay these objects out.

Perhaps container is conflating two things, one which just groups a set of canvasobjects together, and another which lays out a group of canvasobjects.

2020-12-09 23:24 UTC, andydotxyz commented
Hmm, not sure. In a way using a `Layout` is automatic. it adapts to size and reconfigures appropriately.
The "manual" cannot so does require additional work to get a similar outcome...

2020-12-09 23:37 UTC, stuartmscott commented
Both constructors provide something that can hold multiple canvasobjects, so that is the core functionality. The ability to provide a layout for arranging said canvasobjects is an optional extra, which brings me back to `New` and `NewWithLayout`

2020-12-10 09:50 UTC, andydotxyz commented
We reversed the default from  `NewContainer` and `NewContainerWithLayout` in the `fyne` package to `NewContainer` and `NewContainerWithoutLayout` because it was causing confusion.
People were using the default, shorter, constructor and then complaining that layouts didn't work and that containers were difficult to use.
I don't want to revert to that state. Whilst the layout is optional it should not be default omitted.

2020-12-10 10:35 UTC, Jacalz commented
I have one suggestion that might kind of work. Could we not have just one `container.New()` function that takes and the objects. We can then and let manual layout happen with passing a `nil` layout just like we now pass `nil` to icons if we don't want them in for example a `widget.Card` or `widget.Icon`. I know that passing `nil` isn't the most intuitive way, but it is the best solution that I can fink of and it seems sensible in my opinion.

2020-12-10 10:44 UTC, andydotxyz commented
It would probably be an acceptable solution - though it doesn't feel great.
If you're deprecating the old methods we would end up with a deprecation for `NewContainerWIthoutLayout` recommending `container.New(nil)` which feels a bit of a backwards step...

2020-12-11 18:08 UTC, Jacalz commented
Reverted back to the old naming. It seemed pretty clear on the call today that `container.NewWithoutLayout()` might be the best we have at the moment.

2020-12-15 15:17 UTC, stuartmscott approved these changes

2020-12-15 17:37 UTC, andydotxyz requested changes

2020-12-15 17:37 UTC, andydotxyz commented on container.go
> -//
This bank line is required.
Also please add one to the other deprecated notices - it needs to begin a new paragraph.

2020-12-15 17:45 UTC, stuartmscott requested changes

2020-12-15 17:45 UTC, stuartmscott commented on container/container.go
> +// New returns a new Container instance holding the specified CanvasObjects which will be laid out according to the specified Layout.
Needs "Since: 2.0.0" annotations

2020-12-15 18:22 UTC, Jacalz commented
Should be fixed now :)

2020-12-15 18:37 UTC, stuartmscott approved these changes

2020-12-15 21:50 UTC, andydotxyz approved these changes

2020-12-15 22:05 UTC, merged