Deprecations of progress(,inifinite) and entry dialogs
fyne-io/fyne pull request #1643
Opened 2020-12-09 19:07 UTC by Jacalz

### Description:

Deprecates a couple dialogs as discussed and makes Entry dialog use Form dialog.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2020-12-10 13:48 UTC, andydotxyz requested changes
Let's not have fyne_demo be showing off deprecated components.
Either remove them, or update to recommended replacements.

2020-12-11 21:47 UTC, andydotxyz requested changes
Not sure why I didn't notice before, but the Deprecated line needs to have an empty line before it. From the Go docs:

> add a paragraph to its doc comment that begins with Deprecated:

2020-12-13 19:06 UTC, Jacalz commented
Updated this to be rebased on the form changes done in develop. Should  be ready for a re-review now.

2020-12-14 18:08 UTC, andydotxyz approved these changes

2020-12-14 22:16 UTC, merged