Fix tab button layout on mobile
fyne-io/fyne pull request #1962
Opened 2021-02-15 22:11 UTC by stuartmscott

### Description:
Tab buttons were always rendered in a grid of columns, this PR uses a grid of rows when the tab location is leading or trailing

### Checklist:
- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2021-02-20 16:11 UTC, andydotxyz requested changes
Thanks, but not quite the complete solution - 2 cases seem wrong.

Mobile, Portrait, Leading - tabs appear at bottom (should be top)
Mobile, Landscape, Bottom - tabs appear at left (leading), but should be right

2021-02-20 18:13 UTC, stuartmscott commented
Where are you getting these expectations from?

From the ticket (#1310), AppTabs is a combination of two Material Design components;
- Bottom Navigation - which, as the name, suggests doesn't appear at the top.
- Navigation Rail - "The navigation rail is placed on the left side of the screen for left-to-right languages, and on the right side of the screen for right-to-left languages."

2021-02-20 19:23 UTC, andydotxyz commented
> Where are you getting these expectations from?

From how it worked before?

2021-02-20 20:17 UTC, stuartmscott commented
> From how it worked before?

I don't think that is true, Fyne v2.0.0 AppTab on Mobile always moved Leading & Trailing to Bottom (https://github.com/fyne-io/fyne/blob/master/container/apptabs.go#L323):
```go
func (r *appTabsRenderer) adaptedLocation() TabLocation {
	tabLocation := r.container.tabLocation
	if fyne.CurrentDevice().IsMobile() && (tabLocation == TabLocationLeading || tabLocation == TabLocationTrailing) {
		return TabLocationBottom
	}

	return r.container.tabLocation
}
```
And does not have different behaviour for Mobile Portrait vs Mobile Landscape

2021-02-21 12:48 UTC, andydotxyz commented
> Fyne v2.0.0 AppTab on Mobile always moved Leading & Trailing to Bottom

Strange, seems I misremembered how it was previously working.

2021-03-25 15:58 UTC, closed without merging