main menu: add disabled and checked state for menu items
fyne-io/fyne pull request #1975
Opened 2021-02-18 22:28 UTC by tehsphinx

### Description:
This draft / PR is intended to add enabling/disabling of menu items as well as adding the ability to add a check before a menu item.

Fixes #1753
Addresses Enable/Disable part of #682

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.
- [ ] Public APIs match existing style.

2021-02-18 22:30 UTC, tehsphinx commented
Would be happy about some help with tests, especially the objectiveC tests as I don't know objectiveC at all.

2021-03-08 14:49 UTC, andydotxyz requested changes
This looks really great thanks.
Please merge develop in to fix the conflict and address the TODO which has a solution available already.

2021-03-08 14:49 UTC, andydotxyz commented on widget/menu_item.go
> +		// TODO: enable after fixing translucence and alpha channel (https://github.com/fyne-io/fyne/issues/1977)
This is not the right way - it should be changed to a DisabledResource and the colour will update appropriately.
You could look at the existing `Button` widget that disables icons as appropriate.

2021-03-08 14:49 UTC, andydotxyz commented on widget/menu_item.go
> +		r.checkIcon.Translucency = 0
Shouldn't be needed - see above, it will be toggling disabled type for the resource instead.

2021-05-15 12:24 UTC, prifre commented
I wrote on slack: 
"I am looking for how to disable/enable a MenuItem...
I looked at https://github.com/fyne-io/fyne/pull/1975 but I cannot implementation...
What is the status?"
I got reply from tehsphinx  13:32
"fyne has made some decisions that make it unsuitable for our needs, so we moved on to other alternatives."

2021-05-24 09:30 UTC, andydotxyz commented
I will try to pick this up myself to follow the PR in to landing.

2021-05-24 10:08 UTC, andydotxyz commented
Thanks for your hard work on this @tehsphinx, I have resolved the merge conflicts and fixed a couple of issues noted above to hopefully land this cool feature - #2261.

2021-05-24 10:08 UTC, closed without merging