Significantly faster drop downs for widget.Select and widget.SelectEntry
fyne-io/fyne pull request #2181
Opened 2021-04-17 18:50 UTC by Jacalz

### Description:

This moves the popup menus for both `widget.Select` and `widget.SelectEntry` to use the list widget for their popups. This has significant improvements when it comes to performance. Firstly, it allows us to set up the contents dynamically without having to loop through all the options and create menu items for them. It also makes scrolling much more efficient thanks to the List widgets clever caching. As a result, popup now show pretty much instantly no matter how many items there are.

This also allowed for easily exposing the Options as a variable for `widget.SelectEntry`.
There are a few issues to iron out but it is in a kind of working state already.

Fixes #2164

![image](https://user-images.githubusercontent.com/25466657/115123656-57c40980-9fbe-11eb-9ff0-89c00fd9e431.png)

### TODO:
- [ ] Use actual menu items for the list.
- [ ] Open with a more appropriate MinSize.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style.

2021-04-19 16:28 UTC, Jacalz commented
The tests are not perfect, but it should be ready for some reviews at least :slightly_smiling_face:

2021-04-19 17:00 UTC, fpabl0 requested changes
I really love these changes 🥳. I have just added a little suggestion to make it looking better.

2021-04-19 17:05 UTC, Jacalz commented on widget/select_entry.go
> +		return &Label{}
Yeah that's a good idea. I tried to use the actual menu items, but that caused a lot of panics and errors.

2021-04-21 10:31 UTC, andydotxyz commented
This certainly is very cool.
It is a shame that using the menu items was not working.
Is it really outside of the box to consider managing menus internally as collection widgets like a list instead of moving this one usage of menu to a list?

2021-04-21 10:31 UTC, andydotxyz commented
P.S. in the video it seems like the drop-down falls short of the height of the UI, is that a glitch of the demo code?

2021-04-21 13:21 UTC, Jacalz commented
> Is it really outside of the box to consider managing menus internally as collection widgets like a list instead of moving this one usage of menu to a list?

I considered that, but we would be back to square one with needing to loop through and generate MenuItems. Not doing that is probably that largest source for the improvement.

> P.S. in the video it seems like the drop-down falls short of the height of the UI, is that a glitch of the demo code?

No, that's intentional. I put a maximum limit of 10 items as I figured that it was a sensible start. Still need to account for the separator thickness though.

2021-04-21 16:42 UTC, andydotxyz commented
> I considered that, but we would be back to square one with needing to loop through and generate MenuItems. Not doing that is probably that largest source for the improvement.

Not sure I follow you here sorry. I was meaning that the menu widget could add caching, so the loop through items and creating widgets was avoided.

2021-04-21 17:57 UTC, Jacalz commented
> Not sure I follow you here sorry. I was meaning that the menu widget could add caching, so the loop through items and creating widgets was avoided.

What I meant was that, making the menu widget use list would only solve the issue of scrolling. We would still have to pass in menuItems, which would mean that we are back to square one on looping through the Options slice.

With that being said though, it is certainly worth a try now that I think about it. I might have been wrong in my research for this issue and if that's the case, the largest cause for the slowdown could have been the creation of widgets.

2021-04-21 18:15 UTC, Jacalz commented
Hmm, maybe not. I see menu separators potentially becoming an annoying issue to work around. I think I should stick to try and sort out some stuff with the current implementation.

2021-05-19 18:32 UTC, Jacalz commented on widget/select_entry.go
> +		return &Label{}
I think this was solved thanks to the change to the padding in the List.

2021-05-19 18:34 UTC, Jacalz commented
I had to rebase this unfortunately as there were several conflicts. The list is looking a lot better now that the padding is slimmed down:
![better-padding](https://user-images.githubusercontent.com/25466657/118865676-7aa94c80-b8e1-11eb-9f3d-1be310bdf176.gif)
Tests are not updated, which means that they fail. I would still appreciate if some re-reviewing can take place and the n I'll update the tests once there is some feedback on this iteration.

2021-05-20 17:20 UTC, fpabl0 reviewed
With the padless collection PR looks better, but I still think we should create a custom item or maybe use just a canvas.Text? Because it still looks bigger than before:

<img width="320" alt="Captura de Pantalla 2021-05-20 a la(s) 12 10 14" src="https://user-images.githubusercontent.com/12239342/119021733-6313a780-b965-11eb-8e5c-abcc2e71c378.png">

<img width="195" alt="Captura de Pantalla 2021-05-20 a la(s) 12 10 31" src="https://user-images.githubusercontent.com/12239342/119021754-6b6be280-b965-11eb-97cd-daa0ff3ca356.png">

Also, I don't know if it is possible, but should be great if the popup menu list does not have the horizontal padding.

2021-05-20 19:19 UTC, Jacalz commented
Hmm, I'm not quite sure that it should be any smaller. I like the fact that each item is about as big as the Select itself. Smaller menus work great for the entry popup menu, but I think this looks better as it is.

2021-05-20 19:39 UTC, fpabl0 commented
Fair enough. I have just compared it with other apps, and it seems to be smaller:

<img width="358" alt="Captura de Pantalla 2021-05-20 a la(s) 14 38 08" src="https://user-images.githubusercontent.com/12239342/119038681-01f5cf00-b979-11eb-9856-afce3e2499b1.png">

<img width="183" alt="Captura de Pantalla 2021-05-20 a la(s) 14 37 46" src="https://user-images.githubusercontent.com/12239342/119038704-0ae6a080-b979-11eb-90e0-ba81fb38c464.png">

But that's ok, it looks good anyway :), the only thing I would remove is the horizontal padding, as it makes it look unnatural IMHO.

2021-05-22 11:22 UTC, Jacalz commented
It was decided on the call yesterday to instead use caching inside the menu directly. Closing for now.

2021-05-22 11:22 UTC, closed without merging