data/validation: add time format validator
fyne-io/fyne pull request #2196
Opened 2021-04-25 15:23 UTC by Jacalz

### Description:

Adds a validator that I used in [Sparta](https://github.com/Jacalz/sparta) for verifying that dates and times were correct.
Can probably be useful for a lot of other usecases as well :)

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.
- [x] Public APIs match existing style.

2021-04-25 16:08 UTC, stuartmscott requested changes
A useful addition Jacob!

2021-04-25 16:08 UTC, stuartmscott commented on data/validation/time.go
> +		return nil
```suggestion
		_, err := time.Parse(format, text)
		return err
```

2021-04-25 16:15 UTC, Jacalz commented on data/validation/time.go
> +		return nil
Good idea. Thanks 🙂

2021-04-25 16:26 UTC, stuartmscott approved these changes

2021-04-26 16:15 UTC, andydotxyz reviewed
Nice new Validator. 
mid suggest linking to the date format docs though, the Go team made a really good job of describing various formats.

2021-04-26 17:50 UTC, stuartmscott submitted a review, later dismissed

2021-04-26 19:44 UTC, andydotxyz approved these changes

2021-04-26 20:28 UTC, fpabl0 commented
Although it is good to have the link to the go docs. I would prefer to keep this line too:
```
The reference time for the format: Mon Jan 2 15:04:05 -0700 MST 2006.
```
Sometimes, you already know how it works, but you do not remember the reference time, and opening a link just to see it does not seem to be a good experience, does it?

2021-04-27 09:35 UTC, andydotxyz commented
> Although it is good to have the link to the go docs. I would prefer to keep this line too:

That is a good point, I agree

2021-04-27 09:36 UTC, andydotxyz requested changes
I like @fpabl0 comment about re-adding the reference line for quicker doc lookup for the familiar.

2021-04-28 18:35 UTC, Jacalz commented
Good point. Added it back :slightly_smiling_face:

2021-04-28 18:39 UTC, andydotxyz approved these changes
Great thanks

2021-04-28 18:46 UTC, Jacalz commented on data/validation/time_test.go
> +	time := validation.NewTime("2006-01-02")
Good point. I renamed it to `validate`.

2021-04-28 18:51 UTC, fpabl0 approved these changes
LGTM :)

2021-04-28 19:17 UTC, merged