Use OpenGL to draw canvas lines
fyne-io/fyne pull request #2217
Opened 2021-05-04 19:40 UTC by pwiecz

### Description:
Currently lines are drawn on canvas by first rasterizing them onto a texture and then painting the texture on the canvas.
This in some cases may require prohibitive amount of GPU memory.
My motivating use case was displaying a drawing consisting of hundreds of lines where user may zoom in into an arbitrary part of the drawing and drag it around the screen. Without this change the app was crashing running out of memory (and trying to recreate line textures with only parts that are visible was too slow and making dragging operation very choppy).

 
Updates #563

### Checklist:
- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

2021-05-04 20:07 UTC, andydotxyz commented
This is epic thanks so much. I put the following code together and it demonstrates how fast and memory efficient this is in comparison.

Unfortunately the anti-aliasing does not seem to blend to transparent so we get another colour along the edges.
Can this be fixed?

```go
package main

import (
	"image/color"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
)

func main() {
	myApp := app.New()
	myWindow := myApp.NewWindow("Lines")

	l := canvas.NewLine(color.NRGBA{23, 45, 21, 255})
	l.StrokeWidth = 5

	myWindow.SetContent(container.NewWithoutLayout(l))
	myWindow.Resize(fyne.NewSize(500, 500))

	go func() {
		for {
			for x := float32(0); x < 500; x++ {
				l.Position1 = fyne.NewPos(x, 0)
				l.Position2 = fyne.NewPos(500-x, 500)
				l.Refresh()

				time.Sleep(time.Millisecond * 10)
			}
			for y := float32(500); y >= 0; y-- {
				l.Position1 = fyne.NewPos(0, y)
				l.Position2 = fyne.NewPos(500, 500 - y)
				l.Refresh()

				time.Sleep(time.Millisecond * 10)
			}
		}
	}()

	myWindow.ShowAndRun()
}
```

![line](https://user-images.githubusercontent.com/294436/117063448-c32b0c80-ad1c-11eb-8d10-d59449f79fc8.png)

2021-05-04 20:10 UTC, andydotxyz commented
I think also that it may not be central in the space if you see the image above, I have a suspicion that it's being indented from the top/left, what do you think?

2021-05-04 20:22 UTC, pwiecz commented
Sure, I'll be looking into it, but it's getting late here, so not today. :)

2021-05-05 18:02 UTC, pwiecz commented
Hi, can you take a look now?
I've tweaked the alpha blending so that the look match better for both transparent and opaque backgrounds.

2021-05-05 18:44 UTC, Jacalz requested changes
I kicked the tests (GitHub has some weird policy now that we need to approve first-time contributors CI tests to run). Just an FYI that the static analysis tests are failing.

Really nice to see this amazing work. Thank you very much and welcome to our community :slightly_smiling_face:

2021-05-05 19:42 UTC, Jacalz commented
Would be interesting with a benchmark on this. What sort of gains would we expect to see?

2021-05-05 20:18 UTC, pwiecz commented
1) you can easily draw huge lines. say -1'000'000,-1'000'000 -> 1'000'000,1'000'000 - you need only very tiny amount of gpu memory for that.
2) much smoother animations if you have a lot of large lines
Do you have any advise how to have create an non-interactive, "automatic" benchmark, what metric to look at?
I think, it should be easy to create a sample interactive app where one could get a "feel" of performance improvement, but translating it into a simple metric is not obvious to me...

2021-05-05 20:54 UTC, andydotxyz commented
The colour looks much better now thanks :).

I have realised that the offset position issue is not part of this PR, the previous code showed the same issue so I may have to look into it separately.

2021-05-05 20:59 UTC, andydotxyz approved these changes
Super cool. Any chance you know how we can do the same for our (linear?) gradient code too? :)

2021-05-06 04:35 UTC, pwiecz commented
I'm not sure what do you mean by the "offset issues". Can you please describe what's the problem?
Linear gradient seems doable.

2021-05-06 06:13 UTC, Jacalz commented
> I think, it should be easy to create a sample interactive app where one could get a "feel" of performance improvement, but translating it into a simple metric is not obvious to me...

No worries. I was just wondering if you had any concrete benchmarks to feed my curiosity. I gave it a test run and it is obviously feeling very snappy. Nice work 👍

2021-05-06 09:05 UTC, andydotxyz commented
> I'm not sure what do you mean by the "offset issues".

My apologies, it was an issue with my test code :).

2021-05-06 09:15 UTC, Jacalz submitted a review, later dismissed
Looks good to me as well. Amazing work 👍

2021-05-06 09:27 UTC, Jacalz commented
Excuse any potential test failure emails. I'm trying to get the tests to pass over the annoying random test failures (which are not related to this PR in any way).

2021-05-06 09:33 UTC, Jacalz commented
Looks like tests finally passed. Sorry for the inconvenience. We really need to get those random test failures fixed.

2021-05-06 10:06 UTC, andydotxyz requested changes
Oh no! This breaks iOS and Android. Apps won't even boot.
I suspect that the GL shader is not correct for the gomobile driver somehow?

2021-05-06 10:23 UTC, andydotxyz commented
The following patch fixed it locally for me on iOS and Android:

```diff
diff --git a/internal/painter/gl/gl_gomobile.go b/internal/painter/gl/gl_gomobile.go
index abad91d0..2c962265 100644
--- a/internal/painter/gl/gl_gomobile.go
+++ b/internal/painter/gl/gl_gomobile.go
@@ -166,15 +166,15 @@ const (
 
        fragmentLineShaderSource = `
     #version 100
-    uniform vec4 color;
-    uniform float lineWidth;
-    uniform float feather;
+    uniform highp vec4 color;
+    uniform highp float lineWidth;
+    uniform highp float feather;
 
     varying highp vec2 delta;
 
     void main() {
-        float alpha = color.a;
-        float distance = length(delta);
+        highp float alpha = color.a;
+        highp float distance = length(delta);
 
         if (feather == 0.0 || distance <= lineWidth - feather) {
            gl_FragColor = color;
```

2021-05-06 10:27 UTC, pwiecz commented
I am able to test on Android only. It worked on my phones. :(
It makes sense that fragment shaders require precision defined for all the variables.

2021-05-06 11:59 UTC, andydotxyz commented
> I am able to test on Android only. It worked on my phones. :(

That is strange. I was testing on Samsung Galaxy S10 and iPhone 12 mini, which didn't work without the change.
However now I plugged in an older phone, the HTC Desire One and it did work OK without.
Maybe it relates to newer devices?

2021-05-07 19:18 UTC, Jacalz approved these changes
This is working great. Looks good to me.

2021-05-08 18:25 UTC, andydotxyz approved these changes
Yeah that is working great now, thanks so much :)

2021-05-08 18:26 UTC, merged