Fix toolbar to be the standard widget height
fyne-io/fyne pull request #2265
Opened 2021-05-27 11:40 UTC by andydotxyz

To do this right then low profile buttons are fixed as well.
This knocked on to accordion (header) and app/doc tabs.
All positive changes IMHO :)

Fixes #2257

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2021-06-03 13:06 UTC, Jacalz requested changes
Hmm, in general, I think this is a good change, but I am not quite sure that I like the new height of the tabs, though it is hard to say as it might just take some getting used to :)

I also noticed that the tabs change their height when the tab drop-down button appears or disappears. That should probably be fixed.

2021-06-03 13:17 UTC, andydotxyz commented
I cannot replicate any height change - can you provide the steps in detail please?

2021-06-06 18:29 UTC, Jacalz commented
I hope that this should be sufficient:
![jumpy-tabssize](https://user-images.githubusercontent.com/25466657/120936005-dd824c80-c705-11eb-8588-3a96b0f44edc.gif)

2021-06-07 08:05 UTC, andydotxyz commented
Oh, I see it now many thanks.

2021-06-15 17:52 UTC, Jacalz requested changes
Sorry for the late review. This has a conflict with develop.

2021-06-16 18:44 UTC, Jacalz approved these changes
Good stuff. Nice work!

2021-06-17 13:42 UTC, merged