Fixed scrollbar disappearing after changing content
fyne-io/fyne pull request #2303
Opened 2021-06-29 02:44 UTC by s77rt

### Description:
If a scrollbar content is changed, the whole widget content will be replaced (including the scrolling bars, shadows) with just the new content.
The fix is to change only the content of the scrollbar (keeping other objects untouched: scrollbars, shadows, etc)

Fixes #2268

### Checklist:

- [ ] Tests included.
- [X] Lint and formatter run with no errors.
- [X] Tests all pass.

2021-06-29 02:55 UTC, s77rt commented
DocTabs didn't have any scrollbars, making this change will fix the mentioned issue, but will also make DocTabs able to have scrollbars
I like how DocTabs look without scrollbars however with scrollbars it does not look as good (having two bars, bottomline of DocTabs and the scrollbar)
![Screenshot from 2021-06-29 03-53-51](https://user-images.githubusercontent.com/16493223/123729924-a418a900-d88d-11eb-9628-345d2552d309.png)

any ideas?

2021-06-29 22:53 UTC, andydotxyz commented
If content is scrollable it should have scroll bars I think. Otherwise how do people see that the content can scroll. I don’t know if this is an omission in DocTabs, perhaps @stuartmscott can recall?

2021-07-01 09:29 UTC, andydotxyz commented
The test failures need to be addressed before this can be considered. You’ll see the same issues using `go test` locally. You’ll need to copy files from `testdata/failed` over to `testdata/` if the change is intended. It then appears as part of the PR change set.

2021-07-05 12:58 UTC, s77rt commented
okay, but what about the design?
it does not look as good as it was, having two bars is not a good thing IMHO

2021-07-06 09:33 UTC, andydotxyz commented
> it does not look as good as it was, having two bars is not a good thing IMHO

I go with the idea that scrollbars should be used to indicate scrollable content. I don't think we should remove the shadow line as it will not always be scrollable.
Perhaps we will be forced into adding a "Hide Scrollbars" feature?

2021-07-06 13:29 UTC, s77rt commented
or maybe the scrollbar must have it's own dedicated space, not an overlay

2021-07-07 02:44 UTC, zdima commented
I agree the scroll bar doesn't look good with DocTabs, and perhaps we should disable the scroll bar in DocTabs.
However, the DocTabs implementation seems incomplete. The AppTabs and DocTabs are very much alike. But you will see the difference in how the bottom line is handled. In the AppTabs, when "invisible" tab selected, the bottom line moved under "...". The DocTabs bottom line just disappeared. 
Also for both DocTabs and AppTabs, when "invisible" tab selected and user open popup with "...", there is no indication which tab is currently actually.

2021-07-07 21:28 UTC, andydotxyz commented
AppTabs and DocTabs are indeed different. The app tabbing is designed for a more static layout (the main areas of an app at the beginning of a list, others accessible through popup if screen space is too small).
The doc tabs however are designed for lots of documents that may be opened or closed. When you choose an item from the doctabs menu it should scroll in to view.

2021-07-26 16:40 UTC, Jacalz commented
I had a look at this and I think DocTabs certainly look better without the scrollbar. If it isn't too much of a hassle to turn it off for that use case, I think it would be useful to implement that. Is there any broader use case for having that option available in a public API?

2021-07-27 07:34 UTC, andydotxyz commented
If we want this to land in 2.0.4 then we should ignore DocTabs for now, as it does  not exist until 2.1... @Jacalz?

2021-07-27 08:02 UTC, Jacalz commented
That is a very good point. We can tackle that separately.

2021-07-27 08:50 UTC, andydotxyz commented
Hey @s77rt we are looking to prep v2.0.4 this week - do you think we could wrap this up  (fixing tests etc) and we can review DocTabs as we move to 2.1 after.

2021-07-27 13:39 UTC, s77rt commented
Hi,
should i just copy the new results as the expected results

> You’ll need to copy files from testdata/failed over to testdata/ if the change is intended.

2021-07-27 16:48 UTC, andydotxyz commented
> should i just copy the new results as the expected results

Yes. When you push that into the PR we can see the change in expected results to confirm what has altered.

2021-07-27 17:20 UTC, s77rt commented
hmm what about mobile tests?

2021-07-27 17:23 UTC, Jacalz commented
You have to run the tests with `go test -tags mobile .` to get those as well.

2021-07-27 20:24 UTC, andydotxyz requested changes
Great update thanks. However it looks like one or two of the tests have additional changes.

2021-07-27 20:24 UTC, andydotxyz commented on internal/driver/glfw/testdata/windows_hover_object.xml
> +<canvas size="50x45">
I'm not sure that this change is an expected outcome? A lot has changed in this test output which doesn't seem right.

2021-07-27 20:24 UTC, andydotxyz commented on internal/driver/glfw/testdata/windows_no_hover_outside_object.xml
> -<canvas size="200x300">
As above, this test case seems to have changed a lot but I'm not sure why.

2021-07-28 14:30 UTC, andydotxyz commented
Apologies some other features have landed so you'll need to merge develop and re-run the tests.
Perhaps the unexpected change goes away then, I'm not sure what caused it.

2021-07-28 16:05 UTC, s77rt commented
this change also produces a new test failure:
TestWindow_HandleOutsideHoverableObject : (testdata has not been replaced for this one) i think this is something just from my side

2021-07-28 17:00 UTC, andydotxyz commented
I have started to see that test fail as well, so I don't think its your fault.

2021-07-28 17:02 UTC, andydotxyz approved these changes
Excellent thanks

2021-07-28 17:02 UTC, andydotxyz commented
Are you happy too @Jacalz ?

2021-07-28 17:04 UTC, Jacalz approved these changes
Yep :)

2021-07-28 17:11 UTC, merged

2021-07-28 17:12 UTC, andydotxyz commented
FYI for future PRs please don't force push after a review is started as it can make it harder to do subsequent review passes.