Hover fix for List and Tree with Draggable objects
fyne-io/fyne pull request #2308
Opened 2021-07-04 18:52 UTC by zdima

### Description:
Hoverable events won't be delivered to list item or tree item when Draggable widget is used as an Item or as part of Item for a windget.List or a widget.Tree. Since Draggable object is return, the Hoverable events are not fired at all.
As result, the Hoverable events won't be delivered to listItem and treeNode, and hover feedback won't be shown.
 
The issue can be reproduce with https://gist.github.com/zdima/985fc5bd48cc7a78b2d8944c38f27a61

### Checklist:

- [X] Tests included.
- [X] Lint and formatter run with no errors.
- [ ] Tests all pass.

2021-07-04 20:03 UTC, andydotxyz commented
Won't this change break for objects that are Draggable but not Hoverable?

2021-07-04 21:46 UTC, zdima commented
The Draggable objects continue to receive Dragged and DragEnd events.
Also, the most common widgets that uses this interface (list, tree, and split) are working.

2021-07-05 10:33 UTC, andydotxyz commented
Thanks for this. I think the test should be extended to actually show that. I added a little code locally which confirms what you say, but should be included in this PR in to verify going forward.
Note that the drag events should continue even when the drag leaves the source object bounds:

```
	w.mouseMoved(w.viewport, 5, 5)
	w.WaitForEvents()
	assert.Nil(t, d.popDragEvent())
	assert.Nil(t, d.popDragEndEvent())
	assert.Nil(t, h.popMouseInEvent())
	assert.Nil(t, h.popMouseMovedEvent())
	assert.Nil(t, h.popMouseOutEvent())

	w.mouseClicked(w.viewport, glfw.MouseButton1, glfw.Press, 0)
	w.mouseMoved(w.viewport, 6, 6)
	w.WaitForEvents()
	assert.Equal(t, &fyne.DragEvent{PointEvent: fyne.PointEvent{Position: fyne.NewPos(2, 2),
		AbsolutePosition: fyne.NewPos(6, 6)}, Dragged: fyne.NewDelta(1, 1)}, d.popDragEvent())
	assert.Nil(t, d.popDragEndEvent())
	assert.Nil(t, h.popMouseInEvent())
	assert.Nil(t, h.popMouseMovedEvent())
	assert.Nil(t, h.popMouseOutEvent())

	w.mouseMoved(w.viewport, 15, 15)
	w.WaitForEvents()
	assert.Equal(t, &fyne.DragEvent{PointEvent: fyne.PointEvent{Position: fyne.NewPos(11, 11),
		AbsolutePosition: fyne.NewPos(15, 15)}, Dragged: fyne.NewDelta(9, 9)}, d.popDragEvent())
	assert.Equal(t, &desktop.MouseEvent{PointEvent: fyne.PointEvent{Position: fyne.NewPos(1, 1),
		AbsolutePosition: fyne.NewPos(15, 15)}, Button: 1}, h.popMouseInEvent())
	assert.Nil(t, h.popMouseMovedEvent())
	assert.Nil(t, h.popMouseOutEvent())
	assert.Nil(t, d.popDragEndEvent())
```

2021-07-05 10:37 UTC, andydotxyz requested changes
Thanks. This is close. A couple of notes inline but the biggest item is in the conversation - need to check the actual drag callbacks rather than just asserting nil for every one.

2021-07-05 10:37 UTC, andydotxyz commented on internal/driver/glfw/window_test.go
> +	h.SetMinSize(fyne.NewSize(50, 50))
There is no need for these `SetMinSize` lines if you are using a manual layout below.

2021-07-05 10:37 UTC, andydotxyz commented on internal/driver/glfw/window_test.go
> +	assert.Nil(t, h.popMouseOutEvent())
dupe of the line above

2021-07-05 14:10 UTC, andydotxyz requested changes

2021-07-05 14:10 UTC, andydotxyz commented on internal/driver/glfw/window_test.go
> +func TestWindow_HoverableUnderDraggable_DargAcross(t *testing.T) {
This is looking great, just a typo that was introduced sorry.

2021-07-05 14:10 UTC, andydotxyz commented on internal/driver/glfw/window_test.go
> +func TestWindow_HoverableUnderDraggable_Darg_draggableHoverable(t *testing.T) {
typo here too

2021-07-06 08:07 UTC, andydotxyz approved these changes
Great, thanks

2021-07-06 08:07 UTC, merged