Installation capability is removed from go get. Need to use go install instead.
fyne-io/fyne pull request #2642
Opened 2021-11-13 17:10 UTC by aysabzevar

### Description:
"Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead."
Source: https://golang.org/doc/go-get-install-deprecation

The -i flag for go install is also deprecated and go install is enough.

Fixes #(issue)

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

2021-11-13 18:21 UTC, andydotxyz commented
It has not been removed, it has been deprecated. It still works.
The reason this difference matters is because we support Go 1.14, which does not support this new command in the same way.
If you think the documentation should be updated we will have to include both.

2021-11-13 18:22 UTC, andydotxyz requested changes
This won’t work for all our supported versions (back to 1.14)

2021-11-13 19:25 UTC, aysabzevar commented
I am sorry @andydotxyz you are right. I didn't test it carefully.
What do you suggest?

2021-11-13 21:31 UTC, andydotxyz commented
So far we have held off making this change as listing both seemed messy.
However many people are getting confused so probably you are right we should update.
But I think we need to note that this is Go 1.16+ and keep the older docs in a section for older Go (immediately below the new instruction?)

2021-11-14 08:08 UTC, Jacalz requested changes
I agree with @andydotxyz on this. Also found something that seems to be wrong with the current change.

2021-11-14 08:08 UTC, Jacalz commented on README.md
> +    $ go install fyne.io/fyne/v2
For the record, I think this an incorrect change. You still use `go get` to fetch and install dependencies for your modules.

2021-11-17 17:49 UTC, Jacalz commented on README.md
> +    $ go install fyne.io/fyne/v2/cmd/fyne_demo/
It is probably also worth noting that this would fail on Go 1.16 and higher because it requires to add `@latest` at the end when using that command.

2021-11-22 17:37 UTC, Jacalz commented
I would suggest updating to something similar to https://github.com/fyne-io/developer.fyne.io/pull/57 if you would like to continue with this change.

2021-11-29 18:26 UTC, Jacalz commented
@aysabzevar Are you interested in continuing this?

2021-11-30 09:00 UTC, closed without merging