internal: use atomic, sync.Map, and friends for internal structures
fyne-io/fyne pull request #2667
Opened 2021-11-29 05:54 UTC by changkun

### Description:

Optimize the following two cases:

1. atomic access on an individual variable
2. read-heavy cases, such as preference maps

Updates #2359

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2021-11-29 06:38 UTC, Jacalz requested changes
Thanks for this :)

Looks like this has an import problem causing the compiler to complain.

2021-11-29 14:06 UTC, Jacalz approved these changes
Looks good to me. Thanks a lot. All of this really is both easier to read and avoids future issues with forgetting to acquire locks when accessing fields. The performance improvement is certainly very good as well :)

2021-11-30 13:57 UTC, andydotxyz approved these changes

2021-11-30 16:41 UTC, changkun commented
Thanks a lot for the reviewing and I'll merge it now.

2021-11-30 16:41 UTC, merged