Add (URI based) icon and theme reference to theme JSON
fyne-io/fyne pull request #2696
Opened 2021-12-16 21:46 UTC by andydotxyz

Possibility of res:// URI type in the future, but at this time developers can use the theme API directly to use embedded resources.

Fixes #2577

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2022-01-02 14:13 UTC, toaster requested changes
For discussion:
I would prefer a solution where the parsing of the JSON returns any possible error.
Thus, an icon or font URL should trigger the resource loading.
This will increase initial loading times, of course.

Regarding the implementation: I’d left two code clean-up tasks.
- [ ] inline `uriString.uri()`
- [ ] think about consolidation for URI parse error handling

2022-01-02 14:13 UTC, toaster commented on theme/json.go
> +		}
This is exactly the same as in `Font(…)`. Maybe it should be moved into `stringUri.resource()` which then would simply return `nil` if the resource is not present for whatever reason?

2022-01-04 21:38 UTC, andydotxyz commented
> I would prefer a solution where the parsing of the JSON returns any possible error.
> Thus, an icon or font URL should trigger the resource loading.

Hmm, this would be counter to how we handle images (which are not loaded until the rendering needs it).
It is also possible that these are dynamic resources, so the error state may not be consistent over time.

2022-01-17 13:02 UTC, toaster approved these changes

2022-01-17 20:29 UTC, merged