Update go mod.
fyne-io/fyne pull request #2878
Opened 2022-03-30 04:10 UTC by d4x1

### Description:

Fixes #(issue)

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Updated the vendor folder (using `go mod vendor`).
- [ ] Check for binary size increases when importing new modules.

2022-03-30 05:04 UTC, Jacalz requested changes
Thanks a lot for the PR. Are you certain that have actually updated the vendor folder with`go mod vendor`? There are way fewer changes than what I would expect.

Also, I just want to give a friendly tip on how to improve your PR. It is always a good idea to write an informative title for the PR and then write a description about why you want to merge the change. In other words, instead of writing "Update go.mod" you could write something like "Update icns/v2 to 2.2.0" and the write a description about the change and perhaps include a link to https://github.com/JackMordaunt/icns/pull/10. I hope this helps for this and future PRs :)

2022-03-30 06:22 UTC, d4x1 commented
> Thanks a lot for the PR. Are you certain that have actually updated the vendor folder with`go mod vendor`? There are way fewer changes than what I would expect.
> 
> Also, I just want to give a friendly tip on how to improve your PR. It is always a good idea to write an informative title for the PR and then write a description about why you want to merge the change. In other words, instead of writing "Update go.mod" you could write something like "Update icns/v2 to 2.2.0" and the write a description about the change and perhaps include a link to [JackMordaunt/icns#10](https://github.com/JackMordaunt/icns/pull/10). I hope this helps for this and future PRs :)

hi @Jacalz 
Thanks for your advice, and it is helpful.  I update this PR's title and description.  And I have run the command `go mod vendor` in my branch, it is in line with expectations because only one file was updated.

2022-03-30 08:35 UTC, Jacalz commented
> And I have run the command `go mod vendor` in my branch, it is in line with expectations because only one file was updated.

Ah, I see now. Sorry about the fuss. GitHub mobile didn't display that diff for some reason.

2022-03-30 08:37 UTC, Jacalz approved these changes
Looks good to me. Thanks for opening the PR. Also, perhaps perhaps the most important, congratulations for landing your first contribution to Fyne :tada:

2022-03-30 08:37 UTC, merged

2022-04-01 12:57 UTC, andydotxyz commented
Really sorry to say this, but when running fyne package my app icons now look like this on macOS:
![Screenshot 2022-04-01 at 13 55 58](https://user-images.githubusercontent.com/294436/161267781-b37e95ad-3106-480c-af85-70ef732489f2.png)

It seems to only impact some image sizes but is a serious regression.
Can you look into this please @d4x1, or I may have to revert the merge to get back correct icon packaging.

2022-04-01 13:53 UTC, andydotxyz commented
The strangest thing is that if you examine the file all the image sizes are good, but when bundled into the app it doesn't always work well.

2022-04-01 13:59 UTC, andydotxyz commented
The difference between old, working, file and the new seems to be that icons are doubled up on the new file - 2 different DPI for each resolution. Which also results in the file being twice the size...

2022-04-02 03:34 UTC, d4x1 commented
@andydotxyz 
Could you show me how reproduce this bug?

I check this potential bug as follows:
```
go install fyne.io/fyne/v2/cmd/fyne@develop   
fyne version
# output: fyne cli version: v2.1.4-0.20220401172244-2d1c546ccca1 
cd fyne_demo
fyne package
```
And I opened `Fyne Demo.app` and it works fine.
<img width="525" alt="图片" src="https://user-images.githubusercontent.com/5844806/161364101-08f1767d-e7ea-4185-a724-c045bc0b5736.png">

As for the size, the icns v2.2.0 version will produce 10 icon images for incs file, while lower version will produce only 6 images. It's normal that icon file's size is larger then before. That's the reason I update lib icns.  
The icon looks great in Finder. like this:
<img width="239" alt="图片" src="https://user-images.githubusercontent.com/5844806/161364387-9addeb64-6820-477b-819c-43c546a70f51.png">


but when I move it into LaunchPad, it looks like this:
<img width="268" alt="图片" src="https://user-images.githubusercontent.com/5844806/161364370-c39cbc04-f8b6-461f-a93b-11831188ce1d.png">

2022-04-02 16:57 UTC, andydotxyz commented
Using "macOS Big Sur" simply do what you have above. However it is only visible in finder "list view" not the "icon view"

2022-04-02 16:59 UTC, andydotxyz commented
I also cannot replicate on Monterey

2022-04-02 17:02 UTC, andydotxyz commented
If I copy the item built on Big Sur to Monterey the icon is blank and appears corrupted. When I launch it on Monterey this issue appears to fix itself....

2022-04-03 03:34 UTC, d4x1 commented
> 

I have on mac running Big Sur so i cannot directly debug and try to fix this problem. 

I have an idea,  we only need to check whether this 'broken icon'  was really broken.  You can start a new project with lib icns v2.2.0 and convert a simple a PNG to icns file. then  compare the different icns files generated on Big Sur and Montery. 

I think it will be helpful for us to find what's going wrong.

Here is my code:
```go
func main() {
	pngf, err := os.Open("./icon.png")
	if err != nil {
		log.Fatalf("opening source image: %v", err)
	}
	defer pngf.Close()
	srcImg, _, err := image.Decode(pngf)
	if err != nil {
		log.Fatalf("decoding source image: %v", err)
	}
	dest, err := os.Create("./icon.icns")
	if err != nil {
		log.Fatalf("opening destination file: %v", err)
	}
	defer dest.Close()
	if err := icns.NewEncoder(dest).Encode(srcImg); err != nil {
		log.Fatalf("encoding icns: %v", err)
	}
	fmt.Println("end")
}
```

Also, I will try to find the difference between  Big Sur and Montery in dealing with icns files,  it will be not easy( I am not familiar with macOS development).

2022-04-03 12:54 UTC, andydotxyz commented
The icons in the icns are not corrupted, it’s the usage of them that seems to break. As I noted above the difference i can see is how many icons there are of each size in the file, on examination each individual icon is ok, but the app icon rendering is not.

2022-04-04 17:44 UTC, andydotxyz commented
> hi @andydotxyz, As you can see, I haven't changed any logic on rendering icons in OS, so this PR maybe is not the root cause of this problem in theory.

Sorry I am not talking about Fyne's rendering of the app icons, this is in macOS interpretation of the icon file.
This PR is certainly the root cause of the issue because reversing the change removes the problem on Montery.

2022-04-04 17:54 UTC, andydotxyz commented
I have looked at the changelog of the icns project and I think the change is this one:

```
var osTypes = []OsType{
	{ID: "ic10", Size: uint(1024)},
	{ID: "ic14", Size: uint(512)},
	{ID: "ic09", Size: uint(512)},
	{ID: "ic13", Size: uint(256)},
	{ID: "ic08", Size: uint(256)},
	{ID: "ic07", Size: uint(128)}, 
	{ID: "ic12", Size: uint(64)},
+ 	{ID: "icp6", Size: uint(64)},
	{ID: "ic11", Size: uint(32)},
+	{ID: "icp5", Size: uint(32)},
+	{ID: "icp4", Size: uint(16)},
}```

What you can see is that there are new duplicate sizes. In a prior commit I added 2x support for certain sizes so what looks like duplicate is not. However this new change provides two different ways to look  up the 64x64 and 32x32 icons which could be problematic?

Just a thought, maybe we should report this upstream?

2022-04-04 18:05 UTC, andydotxyz commented
Update: I removed the new image formats and that was not the cause of the problem

2022-04-05 05:14 UTC, d4x1 commented
Your testing provides an important clue,  and after searching about this problem, I found some other projects have encountered such problems. 
https://bugreports.qt.io/browse/QTBUG-74497
https://github.com/godotengine/godot/issues/23968

As [wiki](https://en.wikipedia.org/wiki/Apple_Icon_Image_format) says:
<img width="1311" alt="图片" src="https://user-images.githubusercontent.com/5844806/161676468-0320b8ad-942a-4a71-95ef-7d7b286c31b5.png">

It's certainly a macOS's bug(or feature). 

I think the best way to solve this problem is removing icp4、icp5、icp6 icons from lib icns.  And I test it, it works. The icons on Montery are still smooth which is my goal to submit this PR.

How are about your advice?

2022-04-05 09:49 UTC, andydotxyz commented
> I think the best way to solve this problem is removing icp4、icp5、icp6 icons from lib icns. And I test it, it works. The icons on Montery are still smooth which is my goal to submit this PR.

This sounds like the right thing to do. If you could open a PR upstream to do the change we could then use the version that results to resolve the issue for our packager.

2022-04-08 09:03 UTC, andydotxyz commented
Resolved with the latest PR, thanks @d4x1