Add initial notification icons support on Linux and BSD
fyne-io/fyne pull request #2906
Opened 2022-04-09 10:13 UTC by Jacalz

### Description:

This is a WIP PR for adding the support for showing the application icon in notifications on Linux and BSD. The code needs to be tidied up and the caching needs to be improved so that we only write it once and so on. 
![image](https://user-images.githubusercontent.com/25466657/162567322-d401d41a-8386-402f-bb30-16fff7c10f97.png)

It would also be great if we could reuse the application icon if it has been installed into the `/usr/share/icons` path but that might be a bit harder to pull off. Does anyone know an easy way to get the XDG icon corresponding to a specific name?

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [ ] Tests all pass.

2022-05-02 12:16 UTC, andydotxyz requested changes
Nice direction, just a few comments on the uniqueness/icon lookup

2022-05-02 12:16 UTC, andydotxyz commented on app/app_xdg.go
> +	metadata := a.Metadata()
Just use a.Icon(), it first checks settings and then metadata.

2022-05-02 12:16 UTC, andydotxyz commented on app/app_xdg.go
> +	dirPath := filepath.Join(rootCacheDir(), a.uniqueID)
This should be `a.UniqueID()` which does things when there is none set...

2022-05-07 13:21 UTC, Jacalz commented
Sorry for the force push I had to rebase on develop to get the latest CI actions.

2022-05-08 20:53 UTC, andydotxyz approved these changes
Pretty cool, thanks :)

2022-05-09 17:21 UTC, merged