Clean-up: go generate
fyne-io/fyne pull request #2983
Opened 2022-05-17 08:13 UTC by toaster

### Description:

As part of a general code clean-up during OpenGL experiments, I ran `go generate ./...` top level.
I fixed some issues with this and used the latest stringer.
Some mobile generators failed for me because I don’t have an Android SDK environment.
For the same reason, I am not able to test the changes to the mobile `binres_string.go` and `code_string.go` files. The changes look good to me. Any help with testing them is appreciated.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2022-05-17 08:23 UTC, changkun commented on internal/driver/mobile/event/key/code_string.go
> +	_Code_name_8 = "CodeCompose"
FYI: While I merge gomobile in, these names were rewritten to meet the CI lint requirements. Currently, it seems the requirement was removed, and these naming style is acceptable :)

2022-05-17 08:23 UTC, changkun commented on internal/driver/mobile/event/key/code_string.go
> +	_Code_name_8 = "CodeCompose"
Same in other places.

2022-05-17 15:52 UTC, Bluebugs approved these changes

2022-05-24 08:43 UTC, andydotxyz commented
> Some mobile generators failed for me because I don’t have an Android SDK environment.
> For the same reason, I am not able to test the changes to the mobile `binres_string.go` and `code_string.go` files. The changes look good to me. Any help with testing them is appreciated.

I have tried but gomobile generation does not succeed - there is a "go generate" using `gomobile` to create docs that we don't use and have replaced. If you can remove the "go generate" from cmd/fyne/internal/mobile/main.go then it will work OK.

2022-05-24 08:44 UTC, andydotxyz requested changes
As noted in the other comment, "go generate gomobile..." in cmd/fyne/internal/mobile/main.go is blocking this from working as expected on mobile. That should be the last change.

2022-05-26 11:10 UTC, andydotxyz approved these changes
Thanks so much for this

2022-05-26 11:41 UTC, merged