Feature/cloud
fyne-io/fyne pull request #3065
Opened 2022-06-12 21:17 UTC by andydotxyz

Reviving my implementation of cloud hooks.
This is an implementation of proposal https://github.com/fyne-io/proposals/blob/main/cloud.md.

Draft for now, as I test with latest develop and changes in preference API, but should be good to go.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.
- [x] Public APIs match existing style and have Since: line.

2022-06-13 16:08 UTC, Bluebugs commented on data/binding/pref_helper.go
> +func (m *preferencesMap) migratePreferences(p1, p2 fyne.Preferences) {
This look like it is moving data from fyne.Preferences to another. Maybe using src/dst instead of p1/p2 would make it more readable.

2022-06-14 16:42 UTC, Bluebugs approved these changes

2022-06-16 18:00 UTC, andydotxyz commented
I don't think you should have let me away with that @Bluebugs - there are no tests yet!

2022-06-16 18:27 UTC, Bluebugs commented
> I don't think you should have let me away with that @Bluebugs - there are no tests yet!
> 

Indeed and the coverage score even went down. Should have pointed that out.

2022-06-16 18:28 UTC, Bluebugs requested changes
Indeed need tests and get the coverage at least on par if not up!

2022-06-21 22:02 UTC, andydotxyz commented
I think those tests cover most. Not certain if we get an updated report from Coveralls...

2022-06-23 16:11 UTC, merged