Use forms for issue templates
fyne-io/fyne pull request #3132
Opened 2022-07-10 15:59 UTC by Jacalz

### Description:

GitHub now supports using forms for the issue templates. This should help make it easier for the users to fill them out with the relevant information (or more likely harder to not fill it out correctly).

As this is about issue templates, the PR targets the `master` branch.

To see the results of this, see links below:
- [BUG_TEMPLATE](https://github.com/Jacalz/fyne/blob/issues/.github/ISSUE_TEMPLATE/bug_report.yml)
- [FEATURE_TEMPLATE](https://github.com/Jacalz/fyne/blob/issues/.github/ISSUE_TEMPLATE/feature_request.yml)

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2022-07-10 20:35 UTC, andydotxyz commented
Nice new feature - but the 3 items at the top of the bug template seem a little much - especially to confirm code of conduct for every new issue opened.

2022-07-10 20:37 UTC, andydotxyz requested changes
I wonder if there is a way to make the top block easier to approve, or simpler to describe so it's not so much of a hurdle for people opening tickets.

2022-07-10 20:37 UTC, andydotxyz commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +      - label: This issue only relates to a single feature. I will open new issues for any other suggestions.
This should probably refer to features :)

2022-07-11 17:12 UTC, Jacalz commented
Good call. I removed the first check entirely and changed "suggestions" to "features".

2022-07-15 02:24 UTC, andydotxyz approved these changes

2022-07-15 06:43 UTC, merged