Add lock protection for map read/write operations
fyne-io/fyne pull request #3273
Opened 2022-09-19 10:40 UTC by vkuznet

### Description:

Add lock protection for map read/write operations. I made it backward compatible with older go release. Starting with Go 1.19 these changes may be replaced with `sync.Map` (concurrent map).

Fixes #3269

### Checklist:

- [ ] Tests included. **I'm not aware of reliable test procedure for concurrent map read/write operations.**
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

2022-09-19 14:39 UTC, Jacalz requested changes
Thanks for the PR. However, this does unfortunatelly not seem correct. You are creating a new lock object each time so it is not going to guard anything as far as I can see.

The right approach is either to put the mutex in fontCacheItem or switch to `sync.Map` for the map implementation.

2022-09-19 16:08 UTC, vkuznet commented
@Jacalz you're right, I made necessary changes and now lock is part of `fontCacheItem` object.

2022-09-19 18:44 UTC, Jacalz commented
Thanks. There is also the issue that the PR is targeting the master branch. All PRs should target the develop branch per the PR template.

2022-09-20 11:48 UTC, vkuznet commented
@Jacalz , I already see the changes in develop branch, so I think you or someone else has already applied them. Do you need anything from me? Should we close the issue?

2022-09-28 21:15 UTC, andydotxyz commented
If the changes are already on develop then the PR should be closed.
Sorry about the duplication, but we do most of our dev work on that branch.
If we'd been preparing a minor release next we could have brought this in to a release branch, but we are entering the final stages of preparing v2.3.0 so develop is the next branch to release.

2022-09-29 11:16 UTC, closed without merging