Fix panic on invalid file URI #3275
fyne-io/fyne pull request #3308
Opened 2022-10-04 16:49 UTC by ChandanChainani

### Description:

Fixes #(issue)

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style and have Since: line.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Updated the vendor folder (using `go mod vendor`).
- [ ] Check for binary size increases when importing new modules.

2022-10-04 17:27 UTC, Jacalz commented
Thanks for the PR. You have created the PR against the master branch but the PR template states that it should target `develop`. Would you mind changing the target branch to be correct?

2022-10-05 05:32 UTC, Jacalz commented
Also, please add "Fixes #3275" to the description. This will close the issue automatically when the PR is merged

2022-10-05 06:41 UTC, ChandanChainani commented
@Jacalz Thanks, updated as per comments

2022-10-05 08:33 UTC, Jacalz commented on storage/repository/parse.go
> +		return nil, errors.New("not a valid URI")
I would prefer if you check that the code path is invalid and error out in this case. In other words, you keep the code indented as it was before and then have the error handing in an if-statement instead.
```go
if len(s) < 6 {
   return nil, errors.New("not a valid URI")
}
```

2022-10-05 08:37 UTC, Jacalz reviewed
It would also be good if you could rebase on `develop` given that https://github.com/fyne-io/fyne/pull/3301 landed recently and fixed another crash.

2022-10-07 21:48 UTC, Jacalz requested changes
I feel that it would be good to have an actual test case for `Parse` (in the right place) that tests when an error should happen. The new code path is never tested to actually be working unfortunately

2022-10-21 17:10 UTC, andydotxyz approved these changes
Looks good thanks

2022-10-21 17:11 UTC, andydotxyz commented
@Jacalz there is still an outstanding change request from you but I think it's good now.

2022-10-21 18:44 UTC, Jacalz approved these changes
Indeed. Looks good. Thanks for working on this :)

2022-10-21 18:45 UTC, merged