Features/grey font
fyne-io/fyne pull request #3663
Opened 2023-02-14 22:09 UTC by Bluebugs

### Description:
This should reduce the amount of memory allocated and uploaded to the GPU. Hopefully making shaving some of the peak memory consumption off. This is just a small step in improving font rendering in Fyne.

### Checklist:
- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

2023-02-14 22:10 UTC, Bluebugs commented
@Jacalz hopefully this reduce the performance problem you noticed earlier when resizing windows.

2023-02-15 15:27 UTC, andydotxyz requested changes
Just a comment inline about naming.
But it got me wondering, should "gray" in the file names maybe be "uniform" or "singlchannel" or something that indicates that it is about masking on a single colour rather than being grayscale?

2023-02-15 15:27 UTC, andydotxyz commented on internal/painter/gl/draw.go
> +func (p *painter) drawGrayTexture(o fyne.CanvasObject, creator func(canvasObject fyne.CanvasObject) Texture,
Passing in `Color` to something called `Gray` seems a little misleading. Should it be more like `drawUniformTexture` or `DrawSingleChannelTexture`?

2023-02-20 19:22 UTC, Jacalz approved these changes
This seems to make things slightly better, I think. There was not a huge difference on my workstation. Will have a look at this on my laptop tomorrow :)

2023-02-21 16:11 UTC, andydotxyz approved these changes

2023-02-21 16:12 UTC, merged