Better custom dialogs
fyne-io/fyne pull request #3703
Opened 2023-03-05 00:13 UTC by Jacalz

### Description:

This implements the changes needed to be able to create buttons without buttons as well as to use custom button rows.
The deprecation comments for the progressbar dialogs have been updated to mention this new API. 
To make things more consistent, all dialogs now use grids for the button row.

Fixes  #2782, #2127

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style and have Since: line.

2023-03-29 19:00 UTC, andydotxyz requested changes
Overall this looks great, just a couple of small things to tweak.

2023-03-30 18:06 UTC, Jacalz commented
I had to force-push to get the conflict resolved. Everything should be good now :)

2023-03-30 22:13 UTC, andydotxyz commented on dialog/custom.go
> +
Sorry I didn't mean a rename - (`dialog.Custom` was clear enough) it's the missing `var _ Dialog = (*Custom)(nil)`

2023-03-30 22:17 UTC, andydotxyz approved these changes
I wasn't sure about the `Custom` -> `CustomDialog` change, but I see it matches the other types in the package so probably good.

2023-03-31 05:18 UTC, Jacalz commented
The name change was so that we theoretically could add a `Custom` type for the `v2` dialogs in the future (as discussed on the call a few weeks back). On top of that, it is as you say, more in line with the other types :)

2023-03-31 05:22 UTC, Jacalz commented on dialog/custom.go
> +
Indeed. I know. I added the check as well. The rename was for another purpose as per my other comment :)

2023-03-31 05:32 UTC, Jacalz commented
In all honesty, I am not entirely sure how the new dialogs will pan out. I can can revert the name change if you'd like?

2023-03-31 09:39 UTC, andydotxyz commented on dialog/custom.go
> +
I missed the other comment somehow, thanks for getting this all sorted

2023-03-31 09:40 UTC, andydotxyz commented
> In all honesty, I am not entirely sure how the new dialogs will pan out. I can can revert the name change if you'd like?

I think it is consistent with released API names in the package, in which case it should probably stay?

2023-03-31 09:45 UTC, andydotxyz approved these changes

2023-03-31 16:44 UTC, Jacalz commented
Yeah, I agree that consistency wins. I think it makes sense to keep it as it is now and do any aliasing or naming improvements as part of `v2` once it gets traction :)

2023-03-31 16:44 UTC, merged