Add ability to specify the go binary.
fyne-io/fyne pull request #3718
Opened 2023-03-10 19:14 UTC by Bluebugs

### Description:
Some go module only compile with specific version of go compiler. Being able to specify it is quite useful in this situation.

### Checklist:
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:
- [ ] Public APIs match existing style and have Since: line.

2023-03-10 19:25 UTC, andydotxyz requested changes
I don't think `GOBIN` is sufficient is it?
Different versions of Go use different cache / package locations for their root so at least `GOROOT` is missing from this...

2023-03-10 19:30 UTC, Bluebugs commented
In my experiment, it is the `go` command that read the GOROOT environment. So as long as the right binary is executed, it will pick the GOROOT environment variable. Is there any command line argument that you are thinking of? Because otherwise if they are environment variable, they will be propagated.

2023-03-10 19:33 UTC, andydotxyz commented
I share the concern because, in my experience, just changing the binary path is often not sufficient

2023-03-10 19:35 UTC, Bluebugs commented
Yes, but those are environment variable, so you set them when calling fyne in the same way you set GOBIN. There is nothing that the fyne command need to do about those, except to just let them pass through, which it does as default behavior.

2023-03-10 20:19 UTC, andydotxyz commented
If I call a different `go` binary without setting `GOBIN` then I get a pile of compile errors with package versions not matching the compiler. and/or missing packages if the version difference is crossing something like `io/fs` etc.

2023-03-10 20:24 UTC, andydotxyz commented
Oh, maybe that was a special case for when working on Go bugs.
Perhaps I am conflating my work in that with the more developer focused `PATH` vs `GOBIN`, will go read more.

2023-03-10 20:29 UTC, Bluebugs commented
Do you mean, that you are changing the `go` binary itself? I am guessing that in this case you might have not properly updated the environment that those binary use. You can check it with `go env`.

I personally have multiple go installed, but they have different environment set for them (different GOROOT in my case).

2023-03-10 20:34 UTC, andydotxyz commented
I think we are not talking about the same thing here.

From Go docs "Executables are installed in the directory named by the GOBIN environment variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH environment variable is not set. "

So `GOBIN` refers to where user compiled Go executables should be installed... not the Go compiler.
https://pkg.go.dev/cmd/go

2023-03-10 20:53 UTC, Bluebugs commented
Oh, indeed, I had missed that. Let me check.

2023-03-12 03:41 UTC, Bluebugs commented
I picked an completely unused environment variable, GOEXEC. Is there any place where we are documenting the environment variable that fyne is picking up?

2023-03-12 14:07 UTC, andydotxyz commented
Oh I see, you were looking for a new way to specify the compiler... Why not go with one of the ways that already work like GOROOT or suggesting an alias in the documentation.

Surely the best thing is if this picks up the Go version that is currently specified in the users environment?

2023-03-20 17:16 UTC, Bluebugs commented
> Surely the best thing is if this picks up the Go version that is currently specified in the users environment?

Some OS provide multiple install of go in parallel. They do so by providing binary with different name (go1.20, go1.19, ...) and have them all in /usr/bin. Each binary pick its own GOROOT properly. The change is done on the binary name, not on the environment variable.

2023-03-20 18:54 UTC, andydotxyz commented
> > Surely the best thing is if this picks up the Go version that is currently specified in the users environment?
> 
> Some OS provide multiple install of go in parallel. They do so by providing binary with different name (go1.20, go1.19, ...) and have them all in /usr/bin. Each binary pick its own GOROOT properly. The change is done on the binary name, not on the environment variable.

Some might, others don't. So it can be done by a) name change, b) PATH change and c) GOROOT setup.
I don't think we should design a new solution that works for some and not for others.
Why can't we avoid needing to support all of these and just pick up what Go the current env is using?

2023-03-20 19:16 UTC, Bluebugs commented
On Linux, executable are installed in the /usr/bin from distribution package. 
- Changing their name require to manually modify the system after the installation or update of a distribution package.
- All the package get their binary installed in /usr/bin and so the executable have a different name otherwise they would override each other.
- GOROOT only affect the library used by the compiler, not the compiler itself. If you need to pick a different compiler, changing GOROOT does not have any effect on it.

I do not think that any of this solution are comparable with what this PR does. Could you clarify in which scenario this solution will not work?

2023-03-20 19:37 UTC, andydotxyz commented
Sorry, I don't think I explained. I was not saying that a/b/c were ways to *set* the go version - I was saying that these can all be done by different installers and we need to /handle/ these (not require them).
Does that make more sense?

2023-03-22 16:46 UTC, andydotxyz approved these changes

2023-03-22 16:50 UTC, Bluebugs commented on cmd/fyne/internal/commands/build.go
> +			fyneGoModRunner = newCommand(goBin)
Seems like GitHub had some stale data on your side. The patch is using the `GO` environment variable as discussed before.

2023-03-22 16:50 UTC, Bluebugs commented on cmd/fyne/internal/commands/build.go
> +			log.Println("Using GOBIN environment variable for go command:", goBin)
That was removed. Very weird that you didn't get the last version of the patch.

2023-03-22 16:51 UTC, andydotxyz commented on cmd/fyne/internal/commands/build.go
> +			fyneGoModRunner = newCommand(goBin)
Very strange indeed. The approval stands :)

2023-03-22 16:51 UTC, Bluebugs commented on cmd/fyne/internal/commands/build.go
> +			log.Println("Using GOBIN environment variable for go command:", goBin)
Oh, I got confused by GitHub, sorry for the very confused comment :-)

2023-03-22 16:51 UTC, merged