Don't create a windows gui application for `fyne build`
fyne-io/fyne pull request #3781
Opened 2023-04-01 21:46 UTC by hismailbulut

### Description:
Currently `fyne build` and all other commands sets `-H=windowsgui` on windows and this makes debugging nearly impossible.
Because `fyne build` is lower level than others and tries to mimic `go build` it is better to just generate a console app to make debugging easier. After this patch `fyne build` will generate console apps on windows by default but doesn't change others, all `package`, `release` and `install` commands will continue to generate gui apps.

Fixes #3604 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2023-04-01 21:54 UTC, Bluebugs requested changes
I don't think that should be the default behavior even for the build command. If you call fyne build, it is likely from a terminal. So needing an additional window to write logs to when you're already in a terminal isn't really the most likely case. I do understand that you might want still want that behavior in other case, like distributing a debug build. I think in that case we could have a debug flags that will turn on the terminal and potentially additional things that will help collecting debugging information.

2023-04-01 22:09 UTC, hismailbulut commented
> If you call fyne build, it is likely from a terminal. So needing an additional window to write logs to when you're already in a terminal isn't really the most likely case.

This patch actually solves this. -H=windowsgui detaches console from application and we can't see stdout and stderr. With this pacth I am no longer needed to create another debugging outputs (eg. log file), I will just use the terminal I build on and see the output.

> I do understand that you might want still want that behavior in other case, like distributing a debug build.

This is not about distributing debug builds but just only for monitoring stdout for debugging purposes. 

Also this is default only for windows, linux and macos builds all have console, why it should be disabled on windows debug build. I can't just use `go build` because the metadata, app id and version information is important even when debugging the application.
When I say debugging I don't mean something like using delve, just printf

2023-04-01 22:20 UTC, Bluebugs commented
I may have missed it, but this patch always turn on the additional terminal window on windows when using fyne build. I think that should not be a default behavior. It should be only on when you explicitly ask for it.

2023-04-01 22:29 UTC, hismailbulut commented
> I may have missed it, but this patch always turn on the additional terminal window on windows when using fyne build. I think that should not be a default behavior. It should be only on when you explicitly ask for it.

Not additional terminal window, it just prevents detaching from terminal only for `fyne build` and only for windows
But if you wish it can be an option named `-nowindowsgui` or `-nowingui` for `fyne build` and maybe for other commands. But I think it is enough just for `fyne build`

2023-04-02 07:00 UTC, Jacalz requested changes
I agree with @Bluebugs. It is better to keep the current behaviour and instead add a flag to enable the terminal popup for those that want to do so.

2023-04-02 07:04 UTC, Jacalz commented
Just one question: Does passing `-H=windowsgui` mean that you get no terminal output at all even in the terminal you built the application from?

2023-04-02 10:33 UTC, hismailbulut commented
> Just one question: Does passing `-H=windowsgui` mean that you get no terminal output at all, even in the terminal you built the application from?

Yes exactly

2023-04-03 20:09 UTC, andydotxyz commented
> > Just one question: Does passing `-H=windowsgui` mean that you get no terminal output at all, even in the terminal you built the application from?
> 
> Yes exactly

I just tested this because it seemed implausible... That does not seem to be the case.

I just built Fyne Demo using `go build .` in the `cmd/fyne_demo` directory. I then ran it using `./fyne_demo.exe` and it outputted all the logs to the console.

Maybe I did it wrong, but that seems like it is debuggable just like in other OS despite having that flag added.

2023-04-03 22:27 UTC, hismailbulut commented
Please try this on windows
- Go to the cmd/fyne_demo
- Build application with this flag using go `go build -ldflags="-H=windowsgui" .`
- Run `fyne_demo.exe` in same console and see the result, after that build it with just `go build .` without `-H=windowsgui` option and compare them

You will see the difference, First one built with `-H=windowsgui` will immediately detaches from console I run it and start as a separate process (not child). It is impossible to see the output.
Also I can't build my application directly with go because application mostly relies on the metadata that fyne injects, also app id and version information. Currently cmd/fyne always adds this option to go compiler flags and it is impossible to see the output of app built with cmd/fyne. In my opinion it should not be added for `fyne build` by default

2023-04-04 06:25 UTC, andydotxyz commented
I did do it in Windows. Using the install sepcified in our getting started pages (MSYS2 Mingw64).
Perhaps you have a different setup and can provide the details? Maybe it relates to which console app you use...

2023-04-04 15:46 UTC, andydotxyz commented
Apologies, a typo. That was what I was testing. "fyne build ." Produces an app with metadata injected and when executed as "./fyne_demo.exe" it logs to the console it is connected to.

2023-04-04 16:01 UTC, hismailbulut commented
> Apologies, a typo. That was what I was testing. "fyne build ." Produces an app with metadata injected and when executed as "./fyne_demo.exe" it logs to the console it is connected to.

Sorry but this is not what happens to me. I also use msys2 mingw64 and when I built fyne_demo with `fyne build` it just has no console output.

2023-04-05 22:45 UTC, hismailbulut commented
> Can you step through how you launch the built executable? Earlier messages were not explicit enough for me to follow exact steps

Here some information:
- OS: Windows 11
- go version: 1.20.1
- fyne version: 2.3.3
- Terminal: Windows terminal
- I tested using msys2, cmd, powershell

Steps:
- go to the `cmd/fyne_demo`
- run `fyne build`
- run `fyne_demo.exe`

It doesn't show stdout in every shell I tested it, app is detached from console immediately
Output is visible when fyne built with this patch

2023-05-01 11:21 UTC, andydotxyz commented
BTW it is recommended to use metadata rather than LDFlags as they do not work on all platforms even if you can get the commands into the compiler https://developer.fyne.io/started/metadata

2023-06-24 07:36 UTC, Jacalz commented
Perhaps that ldflag could be disabled only when building using `-tags debug`?

2023-06-24 09:16 UTC, andydotxyz commented
Agreed, that was my realisation as well.

2023-06-24 20:52 UTC, andydotxyz commented
Ahaha I finally realised why this was happening to some and not others - cmd and PowerShell fork GUI apps but MSYS2 and Cygwin etc don't.

So for now just use a "unix like" terminal and you'll get the output.

2023-06-29 20:58 UTC, hismailbulut commented
I remember I also tested with msys but I got the same result. But if it works on you then I maybe did something wrong. Maybe because I started msys in cmd shell I don't remember exactly. Anyway IMO it would be nice to have a simple note on the website's Windows development page.

2024-01-07 16:02 UTC, Jacalz commented
It seems to me like we agreed in the team that the previous behavior is more correct. I'll close this now given how long it has been open. We value the contribution a lot and I'm sorry for having to close this.

2024-01-07 16:02 UTC, closed without merging

2024-03-01 10:58 UTC, mondy commented
I have a related problem and would like an option to disable `-H=windowsgui`.
When I run the file generated by `fyne build` from the go program, I do not get any output.
I use [mage](https://magefile.org/) as my build tool. This build tool configuration is written as a go program.

My environment:
* OS: Windows 10
* go version go1.22.0 windows/amd64
* fyne v2.4.4
* Execute on Git Bash

Steps:

Run `fyne build` the following code.

```go
package main

import (
	"fmt"
	"os"

	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	fmt.Fprintln(os.Stdout, "out")
	fmt.Fprintln(os.Stderr, "err")

	a := app.New()
	w := a.NewWindow("win")
	w.SetContent(widget.NewLabel("win"))
	w.ShowAndRun()
}
```

Run `go run` the following code .
I don't use mage to clarify the issue, but mage does the same thing.

```go
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	cmd := `<EXECUTE FILE PATH>`

	c := exec.Command(cmd)
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr

	fmt.Println(c.Run())
}
```

If you run the executable generated by `fyne build` as is, both `out` and `err` will be output, but if you run it via go program, neither `out` nor `err` will be output.

2024-03-01 11:59 UTC, andydotxyz commented
The "fyne" tool is for building the GUI bundle - and Windows will not allow that to log.
You can use the "go build" as you say if you want to run it from the terminal.
This is working as the Microsoft OS requires.

2024-03-01 12:17 UTC, mondy commented
> The "fyne" tool is for building the GUI bundle - and Windows will not allow that to log. You can use the "go build" as you say if you want to run it from the terminal. This is working as the Microsoft OS requires.

There is no way to embed `FyneApp.toml` as metadata when using `go build`.
Or if you embed metadata with ldflags without using `FyneApp.toml`, it will not work when using `fyne build`.
It is silly to rewrite the contents of `FyneApp.toml` to ldflags just to use `go build`.

I think the quickest way to solve this problem is to provide a way to disable `-H=windowsgui` in the `fyne build`.

2024-03-01 14:08 UTC, andydotxyz commented
I think what you are describing is a separate issue. metadata not being included should not be tied to the status of internal build flags. If there isn't already an issue open perhaps it is worth creating one to work through that?

2024-03-01 15:23 UTC, mondy commented
I have tried to create an issue, but the solution is unclear. #4688

2024-03-01 15:28 UTC, andydotxyz commented
Thanks. Issues don't need solutions anyway - that is for us to figure out I guess...