Add ability to show popups (and popup menus) at a relative location
fyne-io/fyne pull request #3936
Opened 2023-06-01 09:40 UTC by andydotxyz

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.
- [x] Public APIs match existing style and have Since: line.

2023-06-02 18:46 UTC, Jacalz requested changes
This seems like a nice and useful addition. Thanks. I just left two comments inline about removing two unnecessary anonymous wrapper functions.

2023-06-02 18:46 UTC, Jacalz commented on widget/popup.go
> +	})
You should be able to drop the wrapper function here.
```suggestion
	withRelativePosition(rel, to, p.ShowAtPosition)
```

2023-06-02 18:46 UTC, Jacalz commented on widget/popup_menu.go
> +	})
The same simplification can be applied here.
```suggestion
	withRelativePosition(rel, to, p.ShowAtPosition)
```

2023-06-02 21:04 UTC, andydotxyz commented
Great suggestions, added

2023-06-03 12:54 UTC, Jacalz approved these changes

2023-06-03 15:54 UTC, merged