Fix/preflistoverwrite
fyne-io/fyne pull request #3970
Opened 2023-06-13 11:23 UTC by andydotxyz

Fix a crash where a preference list overwrite was not not tested.

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2023-06-14 18:54 UTC, Jacalz requested changes
One comment inline about not needing to go through the whole slice if we notice changes.

2023-06-14 18:54 UTC, Jacalz commented on internal/preferences.go
> +					changed = true
Would it not be wise to break out of the loop once we find that it has changed?
```suggestion
					changed = true
					break
```

2023-06-15 10:52 UTC, andydotxyz commented
> Thanks. Nice catch. I left one comment inline about not needing to go through the whole slice if we notice changes.

Excellent thanks - applied

2023-06-15 13:41 UTC, Jacalz approved these changes

2023-06-15 15:56 UTC, merged