Force writing preferences to file when application stops (fixes #3170)
fyne-io/fyne pull request #4043
Opened 2023-07-09 20:37 UTC by nullst

### Description:

Fyne's preferences mechanism implements a debouncing strategy for modifications, it saves the preferences changes to the filesystem at most every 100ms. As explained in issue #3170, the implementation has a bug: if an application modifies at least two preferences (say "A" and "B") during the `OnStopped` lifecycle trigger, we get this:

1. Preference "A" modified, the preferences change listener saves the result to file.
2. Preference "B" modified, the preferences change listener **does not write** the result to file, but instead schedules the save 100ms later.
3. Application exits.
4. After about 100ms, the updated value of the preference "B" would be written to file, but the application is not running anymore. Thus only the value of the preference "A" is updated.

This pull request forces the application to write preferences to file on exit. It does this by adding a new internal lifecycle event, `AfterStoppedTrigger`, which is evaluated after the user-provided `Stopped` lifecycle callback. This modification does not change any public-facing interfaces, only internal implementations.

Fixes #3170.

### Example code

For completeness, here's an example code that demonstrates that the issue #3170 applies to the lifecycle triggers as well. It starts working as intended after this patch.

```go
package main

import (
	"fmt"
	"math/rand"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	application := app.NewWithID("preferences-bug")
	window := application.NewWindow("Preferences bug")

	randomSource := rand.NewSource(time.Now().UnixNano())
	rng := rand.New(randomSource)
	value := rng.Intn(1000)

	label1 := widget.NewLabel(fmt.Sprintf("1st value: %d", application.Preferences().IntWithFallback("one", 0)))
	label2 := widget.NewLabel(fmt.Sprintf("2nd value: %d", application.Preferences().IntWithFallback("two", 0)))
	button := widget.NewButton(fmt.Sprintf("Quit and write %d to both preferences", value), func() {
		application.Quit()
	})
	box := container.New(layout.NewVBoxLayout(), label1, label2, button)
	window.Resize(fyne.NewSize(float32(200), float32(100)))
	window.SetContent(box)

	application.Lifecycle().SetOnStopped(func() {
		application.Preferences().SetInt("one", value)
		application.Preferences().SetInt("two", value)
	})

	window.ShowAndRun()
}
```

### Checklist:

- [ ] Tests included. <- I don't know how to test lifecycle triggers; besides, fyne's tests only set up in-memory preferences, so I don't know how to test that the file is saved correctly.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2023-07-09 20:51 UTC, andydotxyz requested changes
Thanks for looking at this. Unfortunately using the public lifecycle API isn't a workable solution because somebody's app code would override it and break your fix.

2023-07-10 08:56 UTC, nullst commented
>  Unfortunately using the public lifecycle API isn't a workable solution because somebody's app code would override it and break your fix.

Yep, that's why this patch does not use or modify public lifecycle API.

The public interface Lifecycle in `fyne/lifecycle.go` is not changed, I only added an exported function to the (private) structure `Lifecycle` in `fyne/internal/app/lifecycle.go`.

2023-07-10 09:07 UTC, andydotxyz commented
Ah clever, I missed that sorry.
I wonder if a single callback in that instance is sufficient? Because normally the usage of it is separated from the other lifecycle usage (when a developer uses this api it is all in main.go, so easy to read).

So if we do the same thing for another item of code we will break this one. Would a slice of them be suitable? (Also can it use naming that matches, such as `onDestroy` or something... we use "on" prefix to indicate it is a callback)

2023-07-10 09:22 UTC, nullst commented
> So if we do the same thing for another item of code we will break this one.

True, I just followed the approach taken for other lifecycle triggers. Since this is not a public API, it wouldn't be hard to switch to a slice of functions if at some point that would be necessary. I think for most internal purposes there are more direct solutions for executing code at the application exit, here (as discussed in the comments of #3170) the point of the lifecycle approach is to avoid introducing a public `Sync()` method for preferences.

> Also can it use naming that matches, such as onDestroy or something... we use "on" prefix to indicate it is a callback

How about `onStoppedHookExecuted`? More descriptive, no need to explain the priorities between `onStopped` and `onDestroy`, sounds like an internal API name.

2023-07-10 21:22 UTC, andydotxyz reviewed
This looks great.
I think that it could avoid the `atomic.Value` as the setter is always called before quit and it doesn't change through the lifecycle.

2023-07-12 08:23 UTC, nullst commented
>  I think that it could avoid the atomic.Value as the setter is always called before quit and it doesn't change through the lifecycle.

It could, but I used the atomic approach to keep the lifecycle code consistent, thus easier to understand. I can switch to just storing `func ()` if you prefer, though.

2023-07-18 08:31 UTC, nullst commented
I've switched from the atomic.Value approach to storing just a func().

2023-07-22 22:03 UTC, andydotxyz approved these changes
Thanks for this

2023-07-22 22:12 UTC, merged