fixed entry OnChanged callback in propery lock
fyne-io/fyne pull request #4223
Opened 2023-09-07 22:28 UTC by mbaklor

entry callback was in a property lock when selecting and deleting or cutting, my bad, fixed.

Fixes #4209  

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2023-09-08 13:39 UTC, Jacalz requested changes
Thanks for the PR. You right that we shouldn't call user callbacks from within our locks. I comments about improving the code by using read-locks in two place :)

2023-09-08 15:51 UTC, mbaklor commented
lol I absolutely forgot RLock is an option, will fix as soon as I get to it

2023-09-10 07:27 UTC, andydotxyz approved these changes
Looks good thanks.
Just need @Jacalz to approve too and we're good :)

2023-09-10 11:56 UTC, Jacalz approved these changes
Indeed. Thanks for your help with fixing this. It is greatly appreciated :+1:

2023-09-10 11:56 UTC, merged