Adding inner window and multi window containers
fyne-io/fyne pull request #4245
Opened 2023-09-13 17:26 UTC by andydotxyz

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [x] Tests all pass.
- [ ] Public APIs match existing style and have Since: line.

2023-09-13 17:27 UTC, andydotxyz commented
Feel free to test it out. Much testing and docs required I think, but looking for feedback on the API & widgets/layout etc

2023-09-21 21:17 UTC, andydotxyz commented
Same windows build issues as https://github.com/fyne-io/fyne/pull/4262 - unrelated to this code

2023-09-22 17:15 UTC, c1ngular commented
What is this for ? Window embedding ?

2023-09-22 17:32 UTC, andydotxyz commented
> What is this for ? Window embedding ?

for making some content of your app appear within a window inside the app. Like the MDI interfaces from Windows https://en.wikipedia.org/wiki/Multiple-document_interface

2023-09-23 14:11 UTC, c1ngular commented
@andydotxyz  i don't understand , so it is not an actual native window , but an UI widget/container looks like a window visually ?

2023-09-23 15:16 UTC, andydotxyz commented
It looks like a window. Nothing to do with native windows in border or content. See screenshot at the top or try out the fyne_demo in this branch.

2023-09-23 16:02 UTC, c1ngular commented
@andydotxyz  I see , thanks

2023-09-23 18:41 UTC, Jacalz requested changes
Nice work. This is very cool. I left a comment inline but also have some thoughts below. You don't necessarily have to address all of them but I think it might be wise to at least consider them.
- Resizing does not change the mouse cursor. Is that expected?
- I think the title would look better if it was centered in the window instead of being left-aligned.
- I feel like we need some sort of way to control the side of the buttons. It looks a bit out of place with inner windows having buttons to the left and my main window having them to the right. I also wander which of these should be the default? With Windows users being more than Mac-users I suspect that controls on the right side would be preferable?
-  The icon that is displayed in the top right is clickable but does nothing when it is clicked. Should it just be an icon and not a button?
- There seems to be less padding on the top of the window than on the other sides? See image below.

![image](https://github.com/fyne-io/fyne/assets/25466657/c8efc054-c1b7-42c5-b51b-b2b5ac4b634e)
![image](https://github.com/fyne-io/fyne/assets/25466657/a87d203a-d418-4a6c-9828-725d921a5ab5)

Sorry for the rambly sort of review. This really is great stuff but I think it can be made even better :)

2023-09-23 18:41 UTC, Jacalz commented on container/innerwindow.go
> +	pad = theme.Padding()
Are you not setting the value to the same one here?

2023-09-23 19:43 UTC, andydotxyz commented
> * Resizing does not change the mouse cursor. Is that expected?

GLFW does not have a standard cursor for this yet sadly :( - in the future this could be addressed

> I feel like we need some sort of way to control the side of the buttons. It looks a bit out of place with inner windows having buttons to the left and my main window having them to the right. I also wander which of these should be the default? With Windows users being more than Mac-users I suspect that controls on the right side would be preferable? Or do we change default depending on the OS?

Let's address this in a future release and attempt to switch them based on OS. Not sure how we juggle GTK vs KDE vs Enlightenment though!

> There seems to be less padding on the top of the window than on the other sides? See image below.

The padding on 3 sides is the size of padding, on the top it is the window bar - adding more padding didn't look good

I have addressed the other points. If you agree with the summary above we should be good. I can add a ticket to add and detect the button side so it's not forgotten.

2023-09-24 10:44 UTC, Jacalz commented
I think the centered label would have to be centered in the window, not centered between the buttons. Sorry. I understand that it makes the layout a bit more complicated but a relatively simple custom layout should do the job
![image](https://github.com/fyne-io/fyne/assets/25466657/09a6819a-776b-49b7-8991-4d841208d324)

2023-09-24 11:40 UTC, andydotxyz commented
> I think the centered label would have to be centered in the window, not centered between the buttons. Sorry. I understand that it makes the layout a bit more complicated but a relatively simple custom layout should do the job
> 
> ![image](https://github.com/fyne-io/fyne/assets/25466657/09a6819a-776b-49b7-8991-4d841208d324)
> 

If you want the window to be propped open by title that's a simple custom layout - but this really needs truncation.
What should we truncate to if it's centered in the window?

2023-09-24 12:36 UTC, Jacalz commented
Why would having it cantered in the window break truncation? As long as the custom layout handles MinSize correctly, it seems like it should work. All my other windows on my computer has truncation for the title and test in the centre.

2023-09-24 14:58 UTC, andydotxyz commented
Because there is a different space required on the left and right it cannot simply be centered with truncate turned on.
It would have to center as long as there is space and then switch to some other mode when the space needed is less than available if assuming even padding but more than is actually required because the right side is so much smaller in terms of button space.

That seems quite complex and given that left align is standard on Windows 11 I'm tempted to go back to that for now rather than chase this truncation algorithm...

2023-09-24 15:13 UTC, Jacalz approved these changes
Agreed. Approved

2023-09-24 18:14 UTC, Jacalz approved these changes

2023-09-25 05:36 UTC, Jacalz approved these changes

2023-09-25 07:37 UTC, merged