RadioGroup improvements
fyne-io/fyne pull request #4495
Opened 2023-12-29 21:22 UTC by dweymouth

### Description:

Fixes: #3786 #3543 

Improvements to RadioGroup
* Now supports multiple items with the same label, the one tapped will be selected only
* Removed slice of `radioItem` from the widget type (only renderer deals with the radioItems)

### Checklist:

- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style and have Since: line.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Check for binary size increases when importing new modules.

2023-12-29 21:38 UTC, Jacalz commented
Nice. Well done :)

2024-01-07 15:37 UTC, Jacalz commented
A quick look at the failing tests seem to suggest that disabling the widget no longer works as expected?

2024-01-07 16:16 UTC, dweymouth commented
> A quick look at the failing tests seem to suggest that disabling the widget no longer works as expected?

Interesting, I tested the disabling manually and it seems to work fine

2024-01-09 12:30 UTC, andydotxyz commented
Ah, got it - the group is not passing the item state into the items when It creates them - only in the `Refresh()` call is it applied.

I was able to fix some tests as follows, the rest would be passed similarly I imagine:
```go
@@ -15,9 +15,11 @@ var _ desktop.Hoverable = (*radioItem)(nil)
 var _ fyne.Tappable = (*radioItem)(nil)
 var _ fyne.Focusable = (*radioItem)(nil)
 
-func newRadioItem(label string, onTap func(*radioItem)) *radioItem {
+func newRadioItem(label, sel string, onTap func(*radioItem)) *radioItem {
        i := &radioItem{Label: label, onTap: onTap}
        i.ExtendBaseWidget(i)
+
+       i.Selected = sel == label
        return i
 }
```

2024-01-09 16:57 UTC, dweymouth commented
Hmm, good find, not sure how to fix it though as 

> i.Selected = sel == label

is just reintroducing the same issue (all items with the same label would be selected).

Maybe the tests need to be updated since it works in the "real world" so-to-speak

2024-01-09 19:09 UTC, andydotxyz commented
It only works real world because it's refreshing after display for some reason.
Initial state should be correct.
Maybe some of the new code needs to be called on setup?

2024-01-10 00:14 UTC, dweymouth commented
Looks like all remaining test failures are flukes/unrelated

2024-01-10 15:22 UTC, andydotxyz commented
> Looks like all remaining test failures are flukes/unrelated

Agreed. One was fixed on the pending theme widget branch and the other is intermittent.

2024-01-11 19:50 UTC, andydotxyz requested changes
This is looking great - but I think two Refreshes in the tests should not be needed now that the initial state is correct?

2024-01-11 19:50 UTC, andydotxyz commented on widget/radio_group_extended_test.go
> +	radio.Refresh() // sets up selectedIndex
This line should not be needed any more?

2024-01-11 19:50 UTC, andydotxyz commented on widget/radio_group_internal_test.go
> +	radio.Refresh() // sets up selectedIndex
Is this line needed? I don't think it should be

2024-01-11 20:03 UTC, Jacalz approved these changes
I'm happy when Andrew is happy. Thanks for fixing this. I'm glad to see that we allocating less garbage for the GC to deal with :)

2024-01-12 10:12 UTC, andydotxyz approved these changes
Perfect thanks. I'll merge this in over the failing tests then cherry pick the fix off my long standing PR to get this resolved too.

2024-01-12 10:12 UTC, merged