Add ScrollToOffset/GetScrollOffset APIs for List
fyne-io/fyne pull request #4647
Opened 2024-02-18 17:30 UTC by dweymouth

### Description:
These APIs already exist on GridWrap and are useful for two things: 
- saving the state of a list view and re-creating it with a new widget that is scrolled to the same position (eg in apps that have "pages" and can navigate back/forward
- implementing keyboard scrolling when nothing is focused (ie key events hit the window canvas) for apps that have just one list view as their main UI element

Fixes #3544 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style and have Since: line.

2024-02-18 18:30 UTC, Jacalz commented
Nice. Can you add some tests please? :)

2024-02-18 21:50 UTC, dweymouth commented
need to address #4655 for list as well in this PR before merging

2024-02-22 16:08 UTC, dweymouth commented on widget/list.go
> +	} else if h := l.contentMinSize().Height; offset > h {
contentMinSize() is O(n) in the number of items with set heights. If we want to assume that using setItemHeight to make a height shorter than itemMin.Height is not allowed, we can have an O(1) check to skip calling contentMinSize if the offset is within the lower bound on content size of `numItems*itemMin.Height + separatorHeight*numSeparators`

2024-02-23 10:13 UTC, Jacalz requested changes
Nice. I just left a minor code simplification comment inline

2024-02-23 10:13 UTC, Jacalz commented on widget/list.go
> +	}
```suggestion
	if l.Length == nil  {
		return fyne.NewSize(0, 0)
	}
	items := l.Length()
```

2024-03-01 14:23 UTC, andydotxyz commented
Don't we normally omit the `Get` prefix?

2024-03-01 16:23 UTC, andydotxyz commented
> > Don't we normally omit the `Get` prefix?
> 
> Usually, but GridWrap already had a `GetSrollOffset` API so I thought in this case, consistency was better.

A bummer, yes that did slip into 2.4.
Quite right consistency trumps this.

2024-03-01 18:36 UTC, Jacalz commented
Would it not be better to do it correctly here and then deprecate the one with incorrect naming for List?

2024-03-01 18:44 UTC, dweymouth commented
> Would it not be better to do it correctly here and then deprecate the one with incorrect naming for List (and add one with the fright naming of course)?

If we can find a good name, maybe. I do think that having both `ScrollOffset() float64` and `ScrollToOffset(float64)` is confusing naming, even though it matches the "no Get prefix" convention

2024-03-04 08:41 UTC, Jacalz approved these changes
Good point. I'm happy in that case :)

2024-03-04 15:37 UTC, merged