Support Ctrl+[backspace/delete] to delete the word to the left or right of the cursor
fyne-io/fyne pull request #4662
Opened 2024-02-21 01:50 UTC by dweymouth

Fixes #4524 

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2024-02-21 09:12 UTC, Jacalz requested changes
Nice work. A much better implementation than what I had. However, I managed to get it to crash in two ways.

1. Write a single space into the entry and move the cursor to the left.
2. Clicking CTRL + BACKSPACE or CTRL + DELETE will now crash. 

```
panic: runtime error: makeslice: len out of range

goroutine 66 [running]:
fyne.io/fyne/v2/widget.(*RichText).deleteFromTo(0xc00292d800, 0x14, 0x13)
	/var/home/jacob/git/fyne/widget/richtext.go:184 +0x2cf
fyne.io/fyne/v2/widget.(*Entry).deleteWord(0xc003ceb400, 0x1)
	/var/home/jacob/git/fyne/widget/entry.go:907 +0xe5
fyne.io/fyne/v2/widget.(*Entry).registerShortcut.func12({0xc003ceb450, 0xbe0d60})
	/var/home/jacob/git/fyne/widget/entry.go:1214 +0x1c
fyne.io/fyne/v2.(*ShortcutHandler).TypedShortcut(0xc003ceb450, {0xe4c340, 0xc0035ae060})
	/var/home/jacob/git/fyne/shortcut.go:21 +0x6e
fyne.io/fyne/v2/widget.(*Entry).TypedShortcut(0xc00010e360?, {0xe4c340?, 0xc0035ae060?})
	/var/home/jacob/git/fyne/widget/entry.go:963 +0x25
fyne.io/fyne/v2/internal/driver/glfw.(*window).triggersShortcut.func1()
	/var/home/jacob/git/fyne/internal/driver/glfw/window.go:907 +0x24
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x0?)
	/var/home/jacob/git/fyne/internal/driver/common/window.go:35 +0x38
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1 in goroutine 1
	/var/home/jacob/git/fyne/internal/driver/glfw/window.go:961 +0x145
```

2024-04-30 11:14 UTC, Jacalz commented
@dweymouth Did you manage to have another look at it? :)

2024-04-30 15:23 UTC, dweymouth commented
> @dweymouth Did you manage to have another look at it? :)

No I have not. If you happen to find the problem feel free to add a code suggestion :)

2024-05-10 15:00 UTC, dweymouth commented
I fixed the crash I had seen. I've never reproduced the call stack you got @Jacalz so maybe if you get a chance you can test this again and see if you can still make it crash

2024-05-18 12:23 UTC, Jacalz submitted a review, later dismissed
Your fix solves the issue that I was having. This just needs a rebase otherwise LGTM :t-rex:

2024-05-18 14:59 UTC, Jacalz approved these changes

2024-05-18 15:55 UTC, merged