Add IntToFloat (and FloatToInt) in bindings
fyne-io/fyne pull request #4790
Opened 2024-04-18 05:40 UTC by Dorbmon

### Description:

Fixes #4666
The behavior is as same as the Golang native type cast.
### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

According to #4666, it can be used in the situation below:
```go
boundTeaPotCount := binding.NewInt()

slider := widget.NewSliderWithData(0, 130, binding.IntToFloat(boundTeaPotCount))
label := widget.NewLabelWithData(binding.IntToString(boundTeaPotCount))
```

2024-04-18 20:27 UTC, andydotxyz requested changes
Thanks for working on this.

As noted in the file header the `convert.go` is generated - please modify the generator script instead (it's in the same directory).

Apologies for the failure on the web tests, the fix was pushed to develop earlier today.

2024-04-19 05:43 UTC, Dorbmon commented
@andydotxyz Thanks, I have done the change to the generator script.

2024-04-22 10:06 UTC, andydotxyz reviewed
Thanks for this. A few notes to fixup inline

2024-04-22 10:06 UTC, andydotxyz commented on data/binding/convert.go
> +// Since: 2.0
This should say 2.5

2024-04-22 10:06 UTC, andydotxyz commented on data/binding/convert.go
> +// FloatToInt creates a binding that connects a Float data item to a String.
"to an Int" I think.

2024-04-22 10:06 UTC, andydotxyz commented on data/binding/convert.go
> +// FloatToInt creates a binding that connects a Float data item to a String.
Also String->Int on the next line (also remove note to parse?)

2024-04-22 10:06 UTC, andydotxyz commented on data/binding/convert.go
> +// Since: 2.0
Also 2.5

2024-04-22 10:06 UTC, andydotxyz commented on data/binding/gen.go
> +func internalIntToFloat(val int) (float64, error) {
This needs a newline

2024-04-22 10:06 UTC, andydotxyz commented on data/binding/gen.go
> +	// add IntTo
What does this comment mean?

2024-04-23 08:40 UTC, andydotxyz commented on data/binding/gen.go
> +func internalIntToFloat(val int) (float64, error) {
Thanks for updating it, but I don't think you re-generated as the two are still compressed in the output...

2024-04-23 08:52 UTC, Dorbmon commented on data/binding/gen.go
> +	for _, b := range binds {
Fixed

2024-04-23 09:35 UTC, andydotxyz approved these changes
Thanks, this looks close enough ;)
Once we add method ordering in our CI it might fail - but I think our code in there did since we added URI conversion. Happy to land thanks for the contribution.

2024-04-23 10:08 UTC, merged