Fix settings app system theme preview
fyne-io/fyne pull request #4931
Opened 2024-06-13 16:31 UTC by toaster

### Description:

The settings app always shows a dark preview for “system default” no matter what the system actually said.

This PR moves the `app.defaultVariant()` to `internal/app.DefaultVariant()` and thus gives the settings app access to it.

Note that someone need to check that this still compiles for all platforms.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2024-06-13 18:43 UTC, Jacalz approved these changes
Nice :)

2024-06-14 12:46 UTC, andydotxyz reviewed
On this version the system default preview always seems to be dark?

2024-06-14 12:46 UTC, andydotxyz commented
Compiles on Darwin, iOS, Android, WASM - but does not seem to get the preview right on my macOS machine

2024-06-14 13:22 UTC, toaster commented
Found and fixed.

2024-06-14 14:03 UTC, andydotxyz requested changes
Looks good thanks, I just got stuck on naming.

2024-06-14 14:03 UTC, andydotxyz commented on cmd/fyne_settings/settings/appearance.go
> +	themeNameSystemSettings = ""
I was a little confused by the naming - would `themeNameSystem` be OK? It feels like that matches the other keys, leaving the `Label` variant just used for label purposes?

2024-06-14 18:34 UTC, andydotxyz approved these changes

2024-06-14 18:36 UTC, Jacalz approved these changes

2024-06-17 08:30 UTC, merged