internal/driver/glfw: clean the cache periodically.
fyne-io/fyne pull request #5112
Opened 2024-09-04 16:10 UTC by knusbaum

### Description:
The cache is supposed to be cleaned periodically, but the glfw driver does not do this as the mobile driver does.

This commit adds similar logic to the glfw driver as exists in the mobile driver, to periodically clean the cache on paint events.

Fixes #4903

### Notes to Reviewers:

I'm calling `cache.Clean` in a similar way to how it's done in the mobile driver: https://github.com/fyne-io/fyne/blob/5fb3d75695de88c5e0898b0af48b863540295684/internal/driver/mobile/driver.go#L280-L293

I don't fully understand what the boolean value passed to clean represents, or if what I'm doing makes sense. I'm just mimicking the code from mobile.

I have not written regression tests for this, as I'm not familiar enough with the code to confidently do so.

### Checklist:

- [ ] Tests included.
- [x] Lint and formatter run with no errors.
- [ ] Tests all pass.

Not all the tests pass on the current `develop` branch, but this PR does not cause new test failures.

2024-09-07 20:24 UTC, andydotxyz approved these changes
This looks like a good fix. Are you happy we land this before looking at the refactor we discussed @dweymouth ?

2024-09-07 20:26 UTC, dweymouth commented
I suppose, though I suspect we are now doing double cache cleaning work on each clean, since it is calling both cache.Clean and cache.CleanCanvases, which duplicate most of the cleanup tasks. I had thought perhaps cache.CleanCanvases was introduced because cache.Clean couldn't be used in the desktop driver for whatever reason, but if we are calling cache.Clean now, it is very likely CleanCanvases is totally redundant and we should evaluate and remove it

2024-09-07 20:41 UTC, dweymouth commented
From a quick glance it seems the only clean task missing from CleanCanvases is the call to destroyExpiredFontMetrics, so another fix could be just adding that call to CleanCanvases. I would really love if someone who was involved in the initial caching design could review these two funcs more deeply and figure out if we still need the separation between the two

2024-09-09 15:38 UTC, knusbaum commented
> From a quick glance it seems the only clean task missing from CleanCanvases is the call to destroyExpiredFontMetrics, so another fix could be just adding that call to CleanCanvases. I would really love if someone who was involved in the initial caching design could review these two funcs more deeply and figure out if we still need the separation between the two

`CleanCanvases` is already called in the frame draw code:
https://github.com/fyne-io/fyne/blob/master/internal/driver/glfw/loop.go#L78-L98

The issue is that `CleanCanvases` does not run the cache clean for renderers (and maybe other things I haven't checked), but just deletes renderers for *canvases* that have expired or are refreshed (gathered into `deletingObjs`):
https://github.com/fyne-io/fyne/blob/7d813563712924b381ced18c04869c059e2cb4c6/internal/cache/base.go#L132-L145

If we want `CleanCanvases` to clean stale renderers from the cache, it needs to call `destroyExpiredRenderers` as `cache.Clean` does:
https://github.com/fyne-io/fyne/blob/7d813563712924b381ced18c04869c059e2cb4c6/internal/cache/base.go#L51

2024-09-09 15:43 UTC, dweymouth commented
I really hope @andydotxyz or someone else with deeper knowledge into the initial design of the cache and clean tasks can take another look at this, since I don't understand the design well enough to recommend between merging CleanCanvases and Clean into one func, or adding the missed `destroyExpiredRenderers` and `destroyExpiredFontMetrics` to CleanCanvases and continuing to not invoke Clean in the glfw driver.

2024-09-10 15:40 UTC, dweymouth commented
Ah, that would be a breaking public API change, as existing widgets would now have to add this new method to continue to function, so it can't be considered for Fyne 2.x, but could be an option for Fyne 3.x if we ever have the need to introduce other breaking changes. In the meantime, fixing the render cache mechanism is something we will need to pursue. I haven't encountered any issues other than the memory leak you've identified with the current system though.

2024-09-10 15:42 UTC, knusbaum commented
When I have more free time to work on this, I'll try to produce a sample application that demonstrates the other issues. The race condition will probably be hard to trigger, but I should be able to trigger the freeze since that was happening very regularly.

2024-09-10 15:43 UTC, dweymouth commented
Yes, when you have the time please file an issue report for the freezing you're seeing along with a toy app to demonstrate it - as I don't believe any contributors have encountered anything like that and it's an unknown issue right now

2024-09-10 16:43 UTC, dweymouth requested changes
Just commenting to put a block on merging so we don't accidentally merge this and introduce the window-freezing bug @knusbaum described

2024-09-10 16:59 UTC, dweymouth commented
@knusbaum Is your change in your fork to remove the renderer cache on a public branch somewhere? I'd be curious to take a look at it (and maybe considering using it in my fork for my app as well if it's a simple diff)

2024-09-10 19:25 UTC, knusbaum commented
@dweymouth It's not public at the moment. It's mixed in with a bunch of other changes I've made testing out optimizations. Some have worked and others have not been valuable.

I will pull that change out and put it on a public branch. When it's done I'll let you know here.

2024-09-10 23:20 UTC, knusbaum commented
@dweymouth here's my branch with the cache removed, based on the develop branch:
https://github.com/fyne-io/fyne/compare/develop...knusbaum:fyne:remove-renderer-cache?expand=1

I'm not sure everything's fixed, and I haven't updated the tests at all.

2025-01-01 17:21 UTC, dweymouth commented
I wonder if we could somehow only clear the cache for the current window on redraw, if that would avoid issue #5131. Perhaps additional metadata would be needed in the renderer cache to associate them with a window. Also there is a possible complication of a widget being moved from one window to another (do we even support that?)

2025-01-12 14:33 UTC, andydotxyz commented
Can this be re-based on top of the massively-changed develop and then resume the conversation?
I think everything will still be the same, but its possible that the threading changes impact caching and multiple-window handling.

2025-01-24 19:16 UTC, andydotxyz commented
Sorry I have not fed back on this more, just trying to catch up with a few things.

> In applications with multiple windows, interacting with one window will cause the cache to periodically be cleaned (at least, once this PR goes in), but since the second window is never interacted with, it will not be redrawn, and its renderers will expire. It looks like this should not be an issue and that new renderers will be generated on demand. However, this is not happening and the window just freezes. I didn't bother to debug this.

This is a big problem. The updated cache cleans should not pull out so much as to cause an issue in other windows.
We probably need to clean up the cache definitions to remove the overlap - making sure that the "cleanCanvases" only cleans what is specific to that canvas and the overall "clean" can be for those items we know are now not needed anywhere.

I hope that makes sense.

> Also there is a possible complication of a widget being moved from one window to another (do we even support that?)

Yes.

> No, each widget keeps a reference to its renderer. In practice, this is handled by the base widgets. I added a Renderer() method on the Widget interface, and implemented it in the base widget.

We should avoid this. Renderers being cleared up is part of a (should be improved) memory efficiency to clear out the heavy-weight parts of a widget should should be lightweight when not actually being rendered. A widget can, therefore, have multiple different renderers over its lifecycle. If we allow a widget to know its renderer then it can make assumptions and cause unexpected bugs / crashes.

2025-01-25 12:06 UTC, dweymouth commented
@andydotxyz What do you think about adding canvas info to the renderer cache entries, so we could destroy expired renderers only for the window currently being painted? This should avoid the issue, but could lead to other complications, such as the need to have 2 renderers if a widget moves between windows (though this could already be the case)?, as well as an inactive window never having its renderer cache cleaned, which is a partial memory leak (though better than the current case of *no* window having its renderer cache cleaned)

2025-01-25 18:40 UTC, andydotxyz commented
Yes that could be done.
I don't think a cache not being pitched when a window is inactive is a leak - the renders are still "in use" anyway.

A widget changing renderer if it moves to a new window is ok. It doesn't share a graphical context any more so it's pretty much how it should work...

2025-01-26 12:22 UTC, dweymouth commented
Hmm, unfortunately it seems infeasible to parametrize the renderer cache by canvas, since pretty much all of the builtin widgets access their renderers through `cache.Renderer(wid)`. We'd have to convert all those to `cache.RendererForCanvas(wid, fyne.CurrentApp().Driver().CanvasForObject(wid))`, which I believe isn't efficient because CanvasForObject walks the tree, at least sometimes? Though it seems to me that widgets accessing their cached renderer kind of breaks encapsulation and could be something to move away from anyway?

2025-01-26 13:48 UTC, dweymouth commented
I opened a replacement PR here: https://github.com/fyne-io/fyne/pull/5466

2025-01-26 14:58 UTC, dweymouth commented
Superseded by #5466

2025-01-26 14:58 UTC, closed without merging