widget.Table: show first row/column when navigating with keyboard
fyne-io/fyne pull request #5122
Opened 2024-09-08 13:57 UTC by pierrec

Fixes #5088.

### Description:

When a Table has its header(s) shown, keyboard navigation fails to show the first row or column
if the list was scrolled. This is because the header size is always added to the offset even when 
the first row/column is reached. Disabling this for the first row or column fixes the issue.

Fixes #5088

### Checklist:

- [X] Tests included.
- [X] Lint and formatter run with no errors.
- [X] Tests all pass.

2024-09-08 16:28 UTC, andydotxyz requested changes
Thanks so much for fixing this and adding tests.

Unfortunately it only works for when the ID for row or col is 0. 
But also we should ensure the focused cell highlight is visible when the cell index is 1 or above, otherwise the indicator hides behind the header until you reach the first row/col

2024-09-08 17:14 UTC, pierrec commented
I tested by moving too fast, I see the issue now. Will get back to it.

2024-10-16 20:41 UTC, andydotxyz commented
@pierrec can you look at these failures? Because of the force-push it has lost the build history so it is not possible to see where it broke.
Please do avoid force-push after reviews have started so we get more info on what is changing.

2024-12-12 19:29 UTC, pierrec commented
@andydotxyz closing this PR and resubmitting on lastest develop branch.

2024-12-12 19:29 UTC, closed without merging