Proposed v2.5.2 release
fyne-io/fyne pull request #5188
Opened 2024-10-10 12:36 UTC by andydotxyz

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2024-10-10 20:47 UTC, Jacalz requested changes
Does this have the changes that I made for improving theme lookups on Linux? I couldn't see it in the changelog but it seems like something that would be useful.

2024-10-10 20:47 UTC, Jacalz commented on CHANGELOG.md
> +* Sometimes fyne fails to setup dark mode in Windows (#4758)
Shouldn't it be "on Windows"?

2024-10-10 20:56 UTC, andydotxyz commented
> Does this have the changes that I made for improving theme lookups on Linux? I couldn't see it in the changelog but it seems like something that would be useful.

Wasn't that resolved in 2.5.1?

>  * Light/Dark mode detection no longer works on Ubuntu with Fyne 2.5 (#5029)

2024-10-10 20:56 UTC, andydotxyz commented on CHANGELOG.md
> +* Sometimes fyne fails to setup dark mode in Windows (#4758)
thanks, fixed

2024-10-11 06:06 UTC, Jacalz commented
Ah, right. Sorry 😅

2024-10-11 06:07 UTC, Jacalz approved these changes

2024-10-11 07:09 UTC, merged