Fix changes to widget.Form.Items not being reflected on refresh
fyne-io/fyne pull request #5308
Opened 2024-12-11 12:01 UTC by coder-in-go

### Description:
This pull request fixes the FormItem replacement issue in the Form Widget

Fixes  #1966, #1967

### Checklist:
- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2024-12-13 10:05 UTC, Jacalz requested changes
Thanks for the PR. I left two quick comments inline. However, I do also see that this change makes the form tests fail so I think there must be something wrong with what the algorithm is trying to do. Also, it would be nice to add a test for this to verify that it does fix the issues you mention it fixing.

2024-12-13 10:05 UTC, Jacalz commented on widget/form.go
> +			f.setUpValidation(item.Widget, i)
This code is duplicated in both branches. Let's just move it out to before the branch.

2024-12-15 16:13 UTC, geodimm commented on widget/form.go
> +		f.itemGrid.Objects[widgetIndex] = item.Widget
```suggestion
		f.itemGrid.Objects[widgetIndex] = f.createInput(item)
```

I believe this is what breaks the tests

2024-12-24 14:52 UTC, andydotxyz reviewed
Please only use comments in code when 
a) the code is not clear without it
b) there is no way to improve the code so that it would be clear.

We expect code to be self-documenting.

2026-08-14 17:32 UTC, closed without merging