Add a new IndefiniteAnimation
fyne-io/fyne pull request #5344
Opened 2024-12-28 21:14 UTC by dweymouth

### Description:
Adds a new type of animation that has no curve or duration, and simply ticks a function every frame until stopped.
This will be useful in 2.6 to schedule an ongoing "update loop" to run on the main app thread, for example in the `fyne-io/life` repo to replace the goroutine that currently drives the updates.

Fixes #4735 

### Checklist:

- [ ] Tests included. // we don't currently have animation tests
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [x] Public APIs match existing style and have Since: line.

2024-12-29 08:32 UTC, Jacalz requested changes

2024-12-29 08:32 UTC, Jacalz commented on animation.go
> +	}
It would match our style to indent less by instead inverting your if-statement and retuning if it is set up.

2024-12-29 08:32 UTC, Jacalz commented on animation.go
>  }
I'm not a fan of how the methods of different types are interleaved. I'd much rather have all methods for one typ after each other in alphabetical order before the next type.

2024-12-29 08:33 UTC, Jacalz commented
Whoops. Forgot to add the message again. I like the idea of this but I'm not entirely sure if this is the best API for it (not necessarily against but an animation that just passes random curve and duration seems a bit strange). :)

2024-12-29 16:28 UTC, dweymouth commented
> Whoops. Forgot to add the message again. I like the idea of this but I'm not entirely sure if this is the best API for it (not necessarily against but an animation that just passes random curve and duration seems a bit strange). :)

That part is just an implementation detail hidden away from the public API. I did it that way to avoid having to do a much larger code change making the animation scheduler aware of a new type. The implementation details could always be changed later, though if you have any other suggestions for how to implement this, I'm all ears.

2024-12-29 19:14 UTC, Jacalz commented on animation.go
>  }
To clarify: I'd rather have struct, methods, struct, methods and so on. I think that's how Go files generally are structured. Without your latest change it is struct, struct, methods, methods?

2025-01-01 16:32 UTC, andydotxyz requested changes
I think it makes sense to have a clean way to have such an infinite animation, rather than exposing the details in docs or example.

However the word "indefinite" sounds somewhat confusing - would infinite not be more intuitive (and match the progress widget wording).

2025-01-02 09:20 UTC, andydotxyz approved these changes
Great thanks

2025-01-02 09:57 UTC, Jacalz approved these changes

2025-01-02 15:11 UTC, merged